refactor: useInViewport
alibaba/hooks pull request #1040
Opened 2021-07-16 03:43 UTC by brickspert

2021-07-16 03:49 UTC, brickspert commented
fix: #409 #436

2021-07-21 05:56 UTC, awmleer requested changes

2021-07-21 05:56 UTC, awmleer commented on packages/hooks/src/useInViewport/index.zh-CN.md
> +| inViewPort | 是否可见 | `boolean` \| `undefined` |
ViewPort -> Viewport
可以批量查找替换一下……

2021-07-21 05:56 UTC, awmleer commented on packages/hooks/src/useInViewport/index.ts
> +  const [ratio, setRatio] = useState<number>();
`ratio` 现在作为一个 state 了，而且 `threshold` 默认是 0，每一像素的移动都会触发 `setRatio` 这个性能隐患有点大

2021-07-21 06:18 UTC, brickspert commented on packages/hooks/src/useInViewport/index.ts
> +  const [ratio, setRatio] = useState<number>();
不是的，只有在达到设置的阈值的时候，才会触发 ratio 更新。 如果不设置阈值，只有在进入、出去的时候才会更新。

2021-07-21 06:35 UTC, awmleer commented on packages/hooks/src/useInViewport/index.ts
> +  const [ratio, setRatio] = useState<number>();
<img width="743" alt="image" src="https://user-images.githubusercontent.com/16526078/126442558-c5469a70-e752-4eb8-965f-1dac81b23734.png">

2021-07-21 07:39 UTC, awmleer approved these changes

2021-07-21 07:39 UTC, awmleer commented on packages/hooks/src/useInViewport/index.ts
> +  const [ratio, setRatio] = useState<number>();
的确是不会的，我搞错了

2021-07-21 07:39 UTC, merged