refactor: useToggle & useBoolean
alibaba/hooks pull request #1048
Opened 2021-07-20 08:20 UTC by brickspert

2021-07-20 08:22 UTC, brickspert commented
fix: 620

2021-07-24 02:42 UTC, awmleer requested changes

2021-07-24 02:42 UTC, awmleer commented on packages/hooks/src/useToggle/index.ts
> +  set: (value?: T) => void;
`set` 函数的 `value` 参数不能缺省吧……毕竟都已经和 `toggle` 分开了
```suggestion
  set: (value: T) => void;
```

2021-07-25 08:37 UTC, awmleer approved these changes
LGTM

2021-07-25 08:37 UTC, merged