refactor: useLocalStorageState
alibaba/hooks pull request #1057
Opened 2021-07-22 07:42 UTC by brickspert

2021-07-22 07:43 UTC, brickspert commented
fix: #800 #412 #453

2021-07-22 07:51 UTC, brickspert commented
1. When localStorage is forbidden, this hooks will work fine.
2. Add serializer & deserializer

2021-07-26 02:02 UTC, awmleer requested changes

2021-07-26 02:02 UTC, awmleer commented on packages/hooks/src/createUseStorageState/index.ts
> +    } catch {}
报错应该 log 出来给用户看到吧……

2021-07-26 02:02 UTC, awmleer commented on packages/hooks/src/createUseStorageState/index.ts
> +      }
这里要 catch 么……如果真的要 catch 的话，也还是要把 error log 一下的

2021-07-26 02:02 UTC, awmleer commented on packages/hooks/src/createUseStorageState/index.ts
> +      }
同

2021-07-26 04:29 UTC, brickspert commented on packages/hooks/src/createUseStorageState/index.ts
> +      }
删掉了

2021-07-26 05:49 UTC, awmleer approved these changes
LGTM

2021-07-26 05:49 UTC, merged