Feat/use long press
alibaba/hooks pull request #1114
Opened 2021-08-08 05:28 UTC by crazylxr

[[中文版模板 / Chinese template](https://github.com/alibaba/hooks/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

### 💡 Background and solution

监听目标元素的长按事件。

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

2021-08-08 05:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/hooks?pullRequest=1114) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/hooks?pullRequest=1114) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/hooks?pullRequest=1114) it.</sub>

2021-08-12 10:54 UTC, awmleer requested changes

2021-08-12 10:54 UTC, awmleer commented on packages/hooks/src/useLongPress/index.zh-CN.md
> +  delay?: number
看上面 `index.ts` 中 `delay` 是不可缺省的，这里是写错了么

2021-08-12 10:54 UTC, awmleer commented on packages/hooks/src/useLongPress/demo/demo1.tsx
> +  const isPressing = useLongPress(() => setCounter((s) => s + 1), ref, 1000);
`isPressing` 下面好像没用到……？

2021-08-12 10:54 UTC, awmleer commented on packages/hooks/src/useLongPress/index.ts
> +  const timer = useRef<ReturnType<typeof setTimeout>>();
这里为啥不直接用 `number`

```suggestion
  const timer = useRef<number>();
```

2021-08-12 10:54 UTC, awmleer commented on packages/hooks/src/useLongPress/index.ts
> +      }
这里好像不用判断的，直接 clear 就行了

```suggestion
        clearTimeout(timer.current!);
```

2021-08-12 13:34 UTC, crazylxr commented on packages/hooks/src/useLongPress/index.ts
> +  const timer = useRef<ReturnType<typeof setTimeout>>();
看起来更直观一点，能看出来是 setTimeout 的返回值，用 number 也行

2021-08-12 13:34 UTC, crazylxr commented on packages/hooks/src/useLongPress/index.ts
> +      }
有道理，我去掉

2021-08-12 13:34 UTC, crazylxr commented on packages/hooks/src/useLongPress/index.zh-CN.md
> +  delay?: number
我觉得可以缺省一下，默认 1500 ms 你觉得怎么样？

2021-08-12 13:34 UTC, crazylxr commented on packages/hooks/src/useLongPress/demo/demo1.tsx
> +  const isPressing = useLongPress(() => setCounter((s) => s + 1), ref, 1000);
我加个 demo，把 isPressing 用一下。

2021-08-13 07:57 UTC, awmleer commented on packages/hooks/src/useLongPress/index.zh-CN.md
> +);
@brickspert `target` 和 `onLongPress` 两个顺序要不要调整一下……涉及到和 `useClickAway` 保持一致
cc @ttys026

2021-11-03 13:33 UTC, brickspert approved these changes

2021-11-03 13:43 UTC, merged