feat:add useRequest custom cache
alibaba/hooks pull request #1333
Opened 2021-11-29 14:22 UTC by izhangchao

[[中文版模板 / Chinese template](https://github.com/alibaba/hooks/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

2021-11-29 14:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/hooks?pullRequest=1333) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/hooks?pullRequest=1333) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/hooks?pullRequest=1333) it.</sub>

2021-11-30 12:43 UTC, brickspert requested changes

2021-11-30 12:43 UTC, brickspert commented on packages/hooks/src/useRequest/doc/cache/demo/customCache.tsx
> +            console.log('AAAAAAAAAAA', cacheKey)
remove

2021-11-30 12:43 UTC, brickspert commented on packages/hooks/src/useRequest/doc/cache/demo/customCache.tsx
> +    console.log('cacheKey');
remove

2021-11-30 12:43 UTC, brickspert commented on packages/hooks/src/useRequest/doc/cache/cache.zh-CN.md
> +### 自定义缓存
英文文档需要同时更新

2021-11-30 12:43 UTC, brickspert commented on packages/hooks/src/useRequest/src/plugins/useCachePlugin.ts
> +    fetchInstance,
不要替换前面的空格~

2021-11-30 12:43 UTC, brickspert commented on packages/hooks/src/useRequest/src/plugins/useCachePlugin.ts
> +            return !!setCache ? setCache(cacheKey, data) : cache.setCache(cacheKey, cacheTime, data, params);
这里不建议用 useCreation，需要考虑 setCache 的变化。

另外就是 setCache 要不要缓存 cacheTime 和 params。

2021-12-07 13:28 UTC, izhangchao commented
@brickspert

2021-12-07 17:57 UTC, baranwang commented
正需要这个功能，刚想自己PR一个看了一眼就看到这个PR

@izhangchao 你的代码缩紧是四个空格吧，跟项目不一致，所以 没合并

2021-12-08 01:38 UTC, brickspert commented
这个 feature 我可能需要大改一下。

2021-12-20 09:11 UTC, closed without merging