feat: add leftTime for useCountDown
alibaba/hooks pull request #1737
Opened 2022-07-05 07:42 UTC by li-jia-nan

[[中文版模板 / Chinese template](https://github.com/alibaba/hooks/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

### 💡 Background and solution

### 📝 Changelog

`useCountDown` 增加 `leftTime` 参数，支持剩余时间的倒计时，同时优化了一些代码细节：

- `TDate` 类型替换成 `dayjs.ConfigType`，因为dayjs已经定义过了，感觉没必要重复定义
- `new Date().getTime()` 更新为ES6中的 `Date.now()`，性能更好
- `Math.floor()`方法取整更新为位运算，性能更好

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | add leftTime for |
| 🇨🇳 Chinese | 增加 leftTime 参数 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

2022-07-06 01:45 UTC, li-jia-nan commented
有点问题，jest没跑过，我先close掉

2022-07-06 03:48 UTC, li-jia-nan commented
@hchlq @crazylxr 大佬帮忙看下，测试用例跑不过

2022-07-06 05:39 UTC, crazylxr commented
> @hchlq @crazylxr 大佬帮忙看下，测试用例跑不过

你本地跑一下呢，看看能不能过。 不能的话你可能需要看一下是测试用例的问题，还是代码的问题了。

2022-07-06 11:14 UTC, frontlich commented
calcLeftTime 函数最好使用时间戳计算，因为

手机黑屏或者页面失焦的时候，有可能setInterval会暂停执行，当界面重新恢复的时候，pre -interval 计算出来的剩余时间就偏大了

`const startTime = Date.now(); // 记录一下开始时的时间戳`

calcLeftTime函数里
`const passTime = Date.now() - startTime; // 倒计时走过的时间`
`const restTime = leftTime - passTime; // 倒计时剩余的时间`

上面写法可获取到正确的剩余时间

2022-07-06 12:03 UTC, li-jia-nan commented
> calcLeftTime 函数最好使用时间戳计算，因为
> 
> 手机黑屏或者页面失焦的时候，有可能setInterval会暂停执行，当界面重新恢复的时候，pre -interval 计算出来的剩余时间就偏大了
> 
> `const startTime = Date.now(); // 记录一下开始时的时间戳`
> 
> calcLeftTime函数里 `const passTime = Date.now() - startTime; // 倒计时走过的时间` `const restTime = leftTime - passTime; // 倒计时剩余的时间`
> 
> 上面写法可获取到正确的剩余时间

用时间戳的话会出现比较严重的精度问题，比如5000ms倒计时可能是3998，2997，1994，992……这样的情况，可能会带来无法预期的后果

2022-07-07 01:54 UTC, frontlich commented
> > calcLeftTime 函数最好使用时间戳计算，因为
> > 手机黑屏或者页面失焦的时候，有可能setInterval会暂停执行，当界面重新恢复的时候，pre -interval 计算出来的剩余时间就偏大了
> > `const startTime = Date.now(); // 记录一下开始时的时间戳`
> > calcLeftTime函数里 `const passTime = Date.now() - startTime; // 倒计时走过的时间` `const restTime = leftTime - passTime; // 倒计时剩余的时间`
> > 上面写法可获取到正确的剩余时间
> 
> 用时间戳的话会出现比较严重的精度问题，时间间隔不一定能和 `setInterval` 的间隔同步，比如 `5000ms` 倒计时可能是3998，2997，1994，992……这样的情况，可能会带来无法预期的后果

Math.round(3998 / 1000) * 1000 这样可以吧？

2022-07-07 02:31 UTC, li-jia-nan commented
> > > calcLeftTime 函数最好使用时间戳计算，因为
> > > 手机黑屏或者页面失焦的时候，有可能setInterval会暂停执行，当界面重新恢复的时候，pre -interval 计算出来的剩余时间就偏大了
> > > `const startTime = Date.now(); // 记录一下开始时的时间戳`
> > > calcLeftTime函数里 `const passTime = Date.now() - startTime; // 倒计时走过的时间` `const restTime = leftTime - passTime; // 倒计时剩余的时间`
> > > 上面写法可获取到正确的剩余时间
> > 
> > 
> > 用时间戳的话会出现比较严重的精度问题，时间间隔不一定能和 `setInterval` 的间隔同步，比如 `5000ms` 倒计时可能是3998，2997，1994，992……这样的情况，可能会带来无法预期的后果
> 
> Math.round(3998 / 1000) * 1000 这样可以吧？

这样理论上来说对毫秒是可以的，但是不知道会不会影响到 `days`、`hours`、`minutes`、`seconds` 这些单位，我还需要再测试一下

2022-07-07 02:34 UTC, li-jia-nan commented
@hchlq @crazylxr 大佬们麻烦review一下 [1740](https://github.com/alibaba/hooks/pull/1740) 这个pr，修复了测试用例的问题，我这边需要先merge一下才能跑通

2022-07-07 04:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/hooks?pullRequest=1737) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/hooks?pullRequest=1737) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: li-jia-nan<br/>:x: crazylxr<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/hooks?pullRequest=1737) it.</sub>

2022-07-07 04:18 UTC, crazylxr commented
> @hchlq @crazylxr 大佬们麻烦review一下 [1740](https://github.com/alibaba/hooks/pull/1740) 这个pr，修复了测试用例的问题，我这边需要先merge一下才能跑通

好的，已经 merge

2022-07-07 06:19 UTC, li-jia-nan commented
> > @hchlq @crazylxr 大佬们麻烦review一下 [1740](https://github.com/alibaba/hooks/pull/1740) 这个pr，修复了测试用例的问题，我这边需要先merge一下才能跑通
> 
> 好的，已经 merge

OK了，我pull了

2022-07-07 08:54 UTC, hchlq commented on packages/hooks/src/useCountDown/index.ts
> +    // 有 leftTime 就以 leftTime 为主，没有就以 targetDate 为主
英文注释可能会更好～

2022-07-07 08:54 UTC, hchlq commented on packages/hooks/src/useCountDown/index.ts
> +    days: (milliseconds / 86400000) >>> 0,
无符号右移 和 Math.floor 一样吗，建议不修改这里，保持之前的逻辑

2022-07-07 08:54 UTC, hchlq commented on packages/hooks/src/useCountDown/index.ts
> +const calcLeftTarget = (t?: TDate) => {
`t` 这个名字貌似不太好，感觉可以换一个更好的名字～ 【虽然之前是这样的，建议改下】

2022-07-07 09:05 UTC, li-jia-nan commented on packages/hooks/src/useCountDown/index.ts
> +    days: (milliseconds / 86400000) >>> 0,
如果是大于0的值，无符号右移和右移运算符是没区别的，这里我改回去了，保持之前的逻辑

2022-07-07 09:05 UTC, li-jia-nan commented on packages/hooks/src/useCountDown/index.ts
> +const calcLeftTarget = (t?: TDate) => {
改成target了

2022-07-07 09:05 UTC, li-jia-nan commented on packages/hooks/src/useCountDown/index.ts
> +    // 有 leftTime 就以 leftTime 为主，没有就以 targetDate 为主
改成英文了

2022-07-07 09:26 UTC, hchlq commented
好像没啥问题了～ @crazylxr 有空一起帮忙看看呢

2022-07-07 12:45 UTC, miracles1919 reviewed
原本的 test case 不要去改，直接新增 case 就好了。新增的内容，是不能影响原来的功能的

2022-07-07 12:45 UTC, miracles1919 commented on packages/hooks/src/useCountDown/__tests__/index.test.ts
> +const setup = (options: Options = {}) => {
这里不用改吧..

2022-07-07 13:47 UTC, li-jia-nan commented on packages/hooks/src/useCountDown/__tests__/index.test.ts
> +const setup = (options: Options = {}) => {
是不用改……我强迫症，换行不加 return 看着难受……我改回去吧(。-`ω´-)

2022-07-07 15:01 UTC, miracles1919 commented on packages/hooks/src/useCountDown/__tests__/index.test.ts
> +const setup = (options: Options = {}) => {
不是.. 我的意思是，你新增加的 test 放后面

2022-07-10 11:38 UTC, crazylxr commented on packages/hooks/src/useCountDown/demo/demo3.tsx
> + * title: Rest time
英文这个我有点觉得奇怪，咱们的参数是 leftTime，来代表剩余时间，这里用 Rest time 来代表，哪个是比较合理的？

2022-07-10 11:38 UTC, crazylxr commented on packages/hooks/src/useCountDown/index.en-US.md
> +| leftTime   | Rest time, in milliseconds                   | `number`     | -       |
这个 Rest time，我感觉也不是很合适的样子，Rest time 感觉表示休息时间比较多吧，剩余时间可能不太适合。
我查了一下 the rest of time，应该可以表示剩余时间。

2022-07-10 11:38 UTC, crazylxr commented on packages/hooks/src/useCountDown/index.ts
> +const calcLeftTarget = (target?: TDate) => {
calcLeftTarget  这个函数名有点迷惑呀  left target 是啥

2022-07-10 11:38 UTC, crazylxr commented on packages/hooks/src/useCountDown/index.ts
> +  if (left < 0) {
要不把这几行代码搞成一行？

```js
return left < 0 ? 0 : left
```

2022-07-10 11:38 UTC, crazylxr commented on packages/hooks/src/useCountDown/index.ts
> +const calcLeftTime = (leftTime?: number, interval: number = 0): number => {
这里的 leftTime 我觉得是有点问题的。

1. 我看你在代码里所有要调用 calcLeftTime 的地方，都是先判断 leftTime 是 true 才调用的，那 leftTime 为啥要是可选的呢？
2. 如果一个参数是可选的，我觉得应该把它放到后面的参数，必选的放到前面，这个设计就不太对。

2022-07-10 11:38 UTC, crazylxr commented on packages/hooks/src/useCountDown/index.ts
> +    return leftTime ? calcLeftTime(leftTime) : calcLeftTarget(targetDate);
如果 leftTime 是 0 的话这个是不是就有点问题？

2022-07-10 11:38 UTC, crazylxr commented on packages/hooks/src/useCountDown/index.ts
> +    // should work leftTime, and ignored targetDate, If both leftTime and targetDate
`If both leftTime` 的 if 的 i 应该小写吧，

2022-07-10 11:54 UTC, li-jia-nan commented on packages/hooks/src/useCountDown/index.ts
> +const calcLeftTarget = (target?: TDate) => {
> calcLeftTarget

这个是计算剩余的目标时间，原来的命名是calcLeft

2022-07-10 11:55 UTC, li-jia-nan commented on packages/hooks/src/useCountDown/index.ts
> +const calcLeftTarget = (target?: TDate) => {
> calcLeftTarget 这个函数名有点迷惑呀 left target 是啥

这个是计算剩余的目标时间，原来的命名是calcLeft

2022-07-10 11:56 UTC, li-jia-nan commented on packages/hooks/src/useCountDown/index.en-US.md
> +| leftTime   | Rest time, in milliseconds                   | `number`     | -       |
> 这个 Rest time，我感觉也不是很合适的样子，Rest time 感觉表示休息时间比较多吧，剩余时间可能不太适合。 我查了一下 the rest of time，应该可以表示剩余时间。

这里我改成 the rest of time

2022-07-10 11:56 UTC, li-jia-nan commented on packages/hooks/src/useCountDown/index.ts
> +  if (left < 0) {
> 要不把这几行代码搞成一行？
> 
> ```js
> return left < 0 ? 0 : left
> ```

我改一下

2022-07-10 11:57 UTC, li-jia-nan commented on packages/hooks/src/useCountDown/index.ts
> +const calcLeftTime = (leftTime?: number, interval: number = 0): number => {
> 这里的 leftTime 我觉得是有点问题的。
> 
> 1. 我看你在代码里所有要调用 calcLeftTime 的地方，都是先判断 leftTime 是 true 才调用的，那 leftTime 为啥要是可选的呢？
> 2. 如果一个参数是可选的，我觉得应该把它放到后面的参数，必选的放到前面，这个设计就不太对。

确实不应该是可选，因为上面的 calcLeftTarget 函数也是可选的，我为了和之前的逻辑保持一致，就写成可选了，这里我改一下吧

2022-07-10 11:58 UTC, li-jia-nan commented on packages/hooks/src/useCountDown/index.ts
> +    // should work leftTime, and ignored targetDate, If both leftTime and targetDate
> `If both leftTime` 的 if 的 i 应该小写吧，

我改一下

2022-07-10 12:09 UTC, li-jia-nan commented on packages/hooks/src/useCountDown/index.ts
> +    return leftTime ? calcLeftTime(leftTime) : calcLeftTarget(targetDate);
> 



> 如果 leftTime 是 0 的话这个是不是就有点问题？

确实，0应该也走leftTime

2022-07-10 12:14 UTC, li-jia-nan commented on packages/hooks/src/useCountDown/demo/demo3.tsx
> + * title: Rest time
> 英文这个我有点觉得奇怪，咱们的参数是 leftTime，来代表剩余时间，这里用 Rest time 来代表，哪个是比较合理的？

这里我改成The rest of time，和md文档里保持一致

2022-07-11 12:02 UTC, brickspert requested changes
现在代码里面好多地方判断是 leftTime 还是 targetDate

我提个建议：初始化的时候，把 targetDate 转换成 leftTime，这样是不是核心代码就只用处理 leftTime 了？

2022-07-11 12:02 UTC, brickspert commented on packages/hooks/src/useCountDown/index.ts
> +    return isValidTime(leftTime) ? calcLeftTime(leftTime!) : calcLeftTarget(targetDate);
这里 `calcLeftTime(leftTime!)` 应该替换成 `leftTime` ?

2022-07-12 05:53 UTC, li-jia-nan commented
> 现在代码里面好多地方判断是 leftTime 还是 targetDate
> 
> 我提个建议：初始化的时候，把 targetDate 转换成 leftTime，这样是不是核心代码就只用处理 leftTime 了？

我改一下

2022-07-12 05:55 UTC, li-jia-nan commented
@crazylxr @hchlq 根据砖家的建议又改了一版，把 `leftTime` 和 `target` 统一转化成 `leftTime` 了，麻烦 review 一下

2022-07-19 11:26 UTC, brickspert commented on packages/hooks/src/useCountDown/index.ts
> +  }, [leftTime, targetDate, interval]);
```suggestion
  }, [left, interval]);
```

2022-07-19 11:26 UTC, brickspert commented on packages/hooks/src/useCountDown/index.ts
> +        const result = prevState - interval;
这里不能这么算的，因为真正的执行时间，一般是大于 `interval` 的。

还是要用真实的时间来计算的。

如果是这样的话，是不是把 timeLeft 转换成 targetDate 好点，这里需要考虑下~

2022-07-19 11:51 UTC, li-jia-nan commented on packages/hooks/src/useCountDown/index.ts
> +        const result = prevState - interval;
把 timeLeft 转成 targetDate 的话，需要一个开始时间 Date.now()

然后用 Date.now() + timeLeft 就是 targetDate，是这个意思么？

那么问题来了，这个开始时间应该在什么时机申明比较好呢？组件初次加载的时候吗？

2022-07-19 14:24 UTC, li-jia-nan commented on packages/hooks/src/useCountDown/index.ts
> +        const result = prevState - interval;
OK，我转换成 targetDate 了

2022-07-19 14:26 UTC, li-jia-nan commented
@crazylxr @hchlq @brickspert 根据砖家的建议又双叒改了一版，把 leftTime 和 target 统一转化成 targetDate了，麻烦再 review 一下，辛苦！

2022-07-21 09:29 UTC, brickspert commented on packages/hooks/src/useCountDown/index.ts
> +  const startTime = useRef<number>(Date.now());
这里应该是有问题的。

初始化的时候，记录了当前的 Date.now，就是一锤子买卖了，后面一直使用这个 startTime。但是这个 Hooks 是支持多次重启的，这样写的话，多次启动的倒计时都使用了初始化时候的 startTime。

2022-07-21 09:29 UTC, brickspert commented on packages/hooks/src/useCountDown/index.ts
> +  const [timeLeft, setTimeLeft] = useState(calcLeft(startTime.current, leftTime!, targetDate));
这里最好写成 `useState(()=>calcLeft(xxx))`，这样 calcLeft 只会执行一次。

2022-07-22 09:20 UTC, brickspert approved these changes
LGTM

2022-07-22 09:21 UTC, merged