feat: useInViewport (#2060)
alibaba/hooks pull request #2061
Opened 2023-02-14 07:38 UTC by coderluojz

[[中文版模板 / Chinese template](https://github.com/alibaba/hooks/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

2023-02-14 07:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/hooks?pullRequest=2061) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/hooks?pullRequest=2061) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/hooks?pullRequest=2061) it.</sub>

2023-02-20 03:32 UTC, coderluojz commented
@li-jia-nan test ci 跑挂了，怎么解决呢
```
packages/hooks build: node:internal/crypto/hash:71
packages/hooks build:   this[kHandle] = new _Hash(algorithm, xofLen);
packages/hooks build:                   ^
packages/hooks build: Error: error:0308010C:digital envelope routines::unsupported
packages/hooks build:     at new Hash (node:internal/crypto/hash:71:19)
packages/hooks build:     at Object.createHash (node:crypto:133:10)
packages/hooks build:     at module.exports (/home/runner/work/hooks/hooks/node_modules/.pnpm/webpack@4.46.0_webpack-cli@3.3.12/node_modules/webpack/lib/util/createHash.js:135:53)
packages/hooks build:     at NormalModule._initBuildHash (/home/runner/work/hooks/hooks/node_modules/.pnpm/webpack@4.46.0_webpack-cli@3.3.12/node_modules/webpack/lib/NormalModule.js:417:16)
packages/hooks build:     at handleParseError (/home/runner/work/hooks/hooks/node_modules/.pnpm/webpack@4.46.0_webpack-cli@3.3.12/node_modules/webpack/lib/NormalModule.js:471:10)
packages/hooks build:     at /home/runner/work/hooks/hooks/node_modules/.pnpm/webpack@4.46.0_webpack-cli@3.3.12/node_modules/webpack/lib/NormalModule.js:503:5
packages/hooks build:     at /home/runner/work/hooks/hooks/node_modules/.pnpm/webpack@4.46.0_webpack-cli@3.3.12/node_modules/webpack/lib/NormalModule.js:358:12
packages/hooks build:     at /home/runner/work/hooks/hooks/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:373:3
packages/hooks build:     at iterateNormalLoaders (/home/runner/work/hooks/hooks/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
packages/hooks build:     at Array.<anonymous> (/home/runner/work/hooks/hooks/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
packages/hooks build:     at Storage.finished (/home/runner/work/hooks/hooks/node_modules/.pnpm/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
packages/hooks build:     at /home/runner/work/hooks/hooks/node_modules/.pnpm/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
packages/hooks build:     at /home/runner/work/hooks/hooks/node_modules/.pnpm/graceful-fs@4.2.10/node_modules/graceful-fs/graceful-fs.js:123:16
packages/hooks build:     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
packages/hooks build:   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
packages/hooks build:   library: 'digital envelope routines',
packages/hooks build:   reason: 'unsupported',
packages/hooks build:   code: 'ERR_OSSL_EVP_UNSUPPORTED'
packages/hooks build: }
packages/hooks build: Node.js v18.14.1
packages/hooks build: Failed
undefined
/home/runner/work/hooks/hooks/packages/hooks:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  ahooks@3.7.4 build: `gulp && webpack-cli`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

2023-02-20 03:34 UTC, li-jia-nan commented
ci 问题需要 @crazylxr 大佬看看

2023-02-20 10:53 UTC, coderluojz commented
@li-jia-nan 大佬能重新跑一下吗

2023-02-20 10:55 UTC, li-jia-nan commented
ci 有点问题，不是这条 pr 的问题，重跑应该也是不行的

2023-02-21 02:26 UTC, coderluojz commented
@li-jia-nan @crazylxr review please

2023-02-22 03:27 UTC, coderluojz commented
@li-jia-nan  @crazylxr 辛苦大佬们跟进下 pr 流程

2023-02-22 03:43 UTC, crazylxr commented
> @li-jia-nan @crazylxr 辛苦大佬们跟进下 pr 流程

feature 优先级会低一点哈，我们会优先处理 bug，不着急哈

2023-02-28 09:37 UTC, coderluojz commented
@li-jia-nan @crazylxr 大佬辛苦康康review

2023-02-28 10:07 UTC, luo3house commented
![rec](https://user-images.githubusercontent.com/96865086/221821792-7cd26125-958f-4422-bd05-56519be2dd21.gif)

滚动较慢时没有聚焦回 menu1

2023-02-28 10:30 UTC, coderluojz commented
> ![rec](https://user-images.githubusercontent.com/96865086/221821792-7cd26125-958f-4422-bd05-56519be2dd21.gif) [ ![rec](https://user-images.githubusercontent.com/96865086/221821792-7cd26125-958f-4422-bd05-56519be2dd21.gif) ](https://user-images.githubusercontent.com/96865086/221821792-7cd26125-958f-4422-bd05-56519be2dd21.gif) [ ](https://user-images.githubusercontent.com/96865086/221821792-7cd26125-958f-4422-bd05-56519be2dd21.gif)
> 
> 滚动较慢时没有聚焦回 menu1

我已经更改了，辛苦查看

2023-04-02 16:39 UTC, liuyib approved these changes, later dismissed

2023-04-07 02:27 UTC, liuyib commented on packages/hooks/src/useInViewport/index.ts
> +
`target` 支持传数组，这个还没有在文档中说明吧，再完善下文档？ @coderluojz

2023-04-07 02:30 UTC, coderluojz commented on packages/hooks/src/useInViewport/index.ts
> +
好的

2023-04-07 02:53 UTC, liuyib commented on packages/hooks/src/useInViewport/index.zh-CN.md
不只是支持 ref 数组，element 数组也支持。参照这个写下：
![image](https://user-images.githubusercontent.com/38221479/230531563-37eee2a6-2290-473e-94de-88a6e20d777c.png)

@coderluojz  有劳 ❤️

2023-04-07 02:59 UTC, li-jia-nan commented on packages/hooks/src/useInViewport/index.ts
> +      const els = targets.map((element) => getTargetElement(element)).filter(Boolean);
感觉这个 filter(Boolean) 的逻辑可以去掉，放在下面 forEach 里面，判断每一个 item 是否存在，这样会更清晰一点（个人意见，这里不改也可以）

2023-04-07 03:03 UTC, li-jia-nan commented on packages/hooks/src/useInViewport/index.ts
> +      const els = targets.map((element) => getTargetElement(element)).filter(Boolean);
看到下面用 `as Element` 断言了，我猜是推断出来了 undefined 类型所以报错了，如果用 if 判断一下，可以起到类型保护的作用，同时收窄类型，就不需要断言了

2023-04-07 03:05 UTC, liuyib commented on packages/hooks/src/useInViewport/index.ts
> +      const els = targets.map((element) => getTargetElement(element)).filter(Boolean);
> 看到下面用 `as Element` 断言了，我猜是推断出了 `undefined` 类型所以报错了，如果用 if 判断一下，可以起到类型保护的作用，同时收窄类型，就不需要断言了

确实，同意 +1

2023-04-07 03:06 UTC, li-jia-nan commented on packages/hooks/src/useInViewport/index.ts
> +      const targets = Array.isArray(target) ? target : [target];
`targets.map(element => getTargetElement(element))` 这行是不是可以简写成 `targets.map(getTargetElement)` ?

2023-04-07 03:07 UTC, li-jia-nan commented on packages/hooks/src/useInViewport/index.ts
> +      const targets = Array.isArray(target) ? target : [target];
哦不对，不太行，`getTargetElement` 有两个参数，还是不能简写

2023-04-07 03:07 UTC, coderluojz commented on packages/hooks/src/useInViewport/index.ts
> +      const targets = Array.isArray(target) ? target : [target];
good

2023-04-07 03:08 UTC, li-jia-nan commented on packages/hooks/src/useInViewport/index.ts
> +      const targets = Array.isArray(target) ? target : [target];
如果 `getTargetElement` 只有一个参数可以简写一下

2023-04-07 03:14 UTC, li-jia-nan commented
另外这个 callback 是不是可以用 `useMemoizedFn` 缓存一下

2023-04-07 03:16 UTC, coderluojz commented
> 

ok

2023-04-07 03:17 UTC, coderluojz commented
> 另外这个 callback 是不是可以用 缓存一下`useMemoizedFn`

OK

2023-04-07 03:21 UTC, liuyib commented on packages/hooks/src/useInViewport/index.ts
> +      const els = targets.map((element) => getTargetElement(element)).filter(Boolean);
> 感觉这个 `filter(Boolean)` 的逻辑可以去掉，放在下面 `forEach` 里面，判断每一个 item 是否存在，这样会更清晰一点（个人意见，这里不改也可以）

这里的 `filter(Boolean)`，我的理解，如果 targets 里全为假值，可以提前过滤成空数组，然后被 `if (!els.length) return` 提前返回，避免后面 `new IntersectionObserver` 生成不必要的实例

2023-04-07 03:24 UTC, li-jia-nan commented on packages/hooks/src/useInViewport/index.ts
> +      const els = targets.map((element) => getTargetElement(element)).filter(Boolean);
> 这里的 `filter(Boolean)`，我的理解，如果 targets 里全为假值，可以提前过滤成空数组，然后被 `if (!els.length) return` 提前返回，避免后面 `new IntersectionObserver` 生成不必要的实例

嗯，可以的，filter 可以保留，两头都判断也没啥问题

2023-04-07 03:34 UTC, li-jia-nan commented on packages/hooks/src/useInViewport/index.ts
> +      const els = targets.map(getTargetElement<Element>).filter(Boolean);
这里不能简写的，还原一下吧

2023-04-07 03:35 UTC, li-jia-nan commented on packages/hooks/src/useInViewport/demo/demo3.tsx
> +  const callback = useMemoizedFn((entry) => {
我的意思是用 useMemoizedFn 包一下实现中的 callback，demo 可以不用改

2023-04-07 03:37 UTC, li-jia-nan commented on packages/hooks/src/useInViewport/demo/demo3.tsx
> +  const callback = useMemoizedFn((entry) => {
`const observeCallback = useMemoizedFn(callback);`

比如这样

2023-04-07 03:47 UTC, li-jia-nan commented on packages/hooks/src/useInViewport/index.ts
> +  const observeCallback = callback && useMemoizedFn(callback);
这个语法有问题吧，react hook 不能在条件语句中使用，这里应该不需要判断

2023-04-07 04:19 UTC, coderluojz commented on packages/hooks/src/useInViewport/index.ts
> +  const observeCallback = callback && useMemoizedFn(callback);
callback 是可选项 可能会存在 undefined 所以这里应该是不行的  只能通过外部调用的时候手动添加 useMemoizedFn

2023-04-07 04:24 UTC, li-jia-nan commented
如果不用 `useMemoizedFn` 包的话，是不是应该把 `callback` 放进依赖数组监听一下？否则引用变了 hook 不会重新执行

2023-04-07 04:28 UTC, coderluojz commented
> 如果不用 `useMemoizedFn` 包的话，是不是应该把 `callback` 放进依赖数组监听一下？否则引用变了 hook 不会重新执行

ok的

2023-04-07 10:15 UTC, liuyib requested changes
辛苦再完善下测试用例，callback 和 数组形式的 target 都要测到

2023-04-18 09:49 UTC, coderluojz commented
> 辛苦再完善下测试用例，callback 和 数组形式的 target 都要测到 @coderluojz

已添加测试用例 辛苦review

2023-04-18 15:07 UTC, liuyib approved these changes

2023-05-08 15:45 UTC, liuyib commented
@coderluojz  不用重复一直 Merge branch 'master' into master 哈，merge 之前会有人更新的 ~

2023-06-06 05:11 UTC, coderluojz commented
> @coderluojz 不用一直重复 Merge branch 'master' into master 哈，merge 之前会有人更新的 ~

好慢~

2023-06-06 06:11 UTC, liuyib commented
> > @coderluojz 不用一直重复 Merge branch 'master' into master 哈，merge 之前会有人更新的 ~
> 
> 好慢~

不着急哈，有 merge 权限的成员最近工作比较忙呢

2023-07-12 01:18 UTC, crazylxr approved these changes

2023-07-12 01:18 UTC, merged