style: change the default import to import on demand
alibaba/hooks pull request #2230
Opened 2023-06-21 08:34 UTC by askwuxue

[[中文版模板 / Chinese template](https://github.com/alibaba/hooks/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [x] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | change the default import to import on demand          |
| 🇨🇳 Chinese | 修改默认导入为按需导入   |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

2023-06-21 08:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/hooks?pullRequest=2230) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/hooks?pullRequest=2230) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/hooks?pullRequest=2230) it.</sub>

2023-06-21 10:25 UTC, liuyib requested changes

2023-06-21 10:25 UTC, liuyib commented on packages/hooks/src/useRequest/src/utils/cache.ts
这里没必要变动，回退下吧，尽量一个 PR 只做一件事

2023-06-21 14:48 UTC, askwuxue commented on packages/hooks/src/useRequest/src/utils/cache.ts
好的，后面的提交已经回退。这个地方我觉得修改后可能更精简一点。

2023-06-25 00:54 UTC, liuyib approved these changes

2023-07-05 11:50 UTC, crazylxr approved these changes

2023-07-05 11:50 UTC, merged