feat: add useEventTarget
alibaba/hooks pull request #300
Opened 2020-03-16 07:27 UTC by n0ruSh

[RFC useEventTarget #295的实现](https://github.com/umijs/hooks/issues/295)

2020-03-16 13:50 UTC, brickspert requested changes

2020-03-16 13:50 UTC, brickspert commented on packages/hooks/src/useEventTarget/demo/demo1.tsx
> + * desc: controlled Input component with initial value and reset functionality
首字母大写

2020-03-16 13:50 UTC, brickspert commented on packages/hooks/src/useEventTarget/demo/demo1.tsx
> + * desc: controlled Input component with initial value and reset functionality
首字母大写

2020-03-16 13:50 UTC, brickspert commented on packages/hooks/src/useEventTarget/demo/demo2.tsx
> + * desc: controlled Input component with number input only
首字母大写

2020-03-16 13:50 UTC, brickspert commented on packages/hooks/src/useEventTarget/index.ts
> +export default <T>(initialValue: T, transformer?: (value: T) => T): [
transformer 的输入和输出也可以类型不同吧。

2020-03-16 13:50 UTC, brickspert commented on packages/hooks/src/useEventTarget/index.ts
> +export default <T>(initialValue: T, transformer?: (value: T) => T): [
initialValue 应该也是可选的。

2020-03-16 13:50 UTC, brickspert commented on packages/hooks/src/useEventTarget/index.ts
> +  const reset = () => setValue(initialValue);
reset 用 useCallback 包一下，让它不要变化，用户用起来会好点。

2020-03-16 13:50 UTC, brickspert commented on packages/hooks/src/useEventTarget/index.ts
> +  const onChange = (e: EventTarget<T>) => {
用 useCallback 包一下

2020-03-16 13:59 UTC, n0ruSh commented on packages/hooks/src/useEventTarget/index.ts
> +export default <T>(initialValue: T, transformer?: (value: T) => T): [
> transformer 的输入和输出也可以类型不同吧。

不可以的吧。。对于同一个组件来说，原来的值是什么类型，转换下应该还是那个类型吧。例如Input的value是字符串，转换下再传回去的应该也还是字符串，不可能转成一个其他类型像数组或者对象回去吧。

2020-03-16 14:36 UTC, brickspert commented on packages/hooks/src/useEventTarget/index.ts
> +export default <T>(initialValue: T, transformer?: (value: T) => T): [
value 和 onChange 不一定非要一起用。比如

```
const [{value, onChange}] = useEventTarget('',  (t)=>!!t );

<Input onChange={onChange} />
<div>{value}</div>
```

2020-03-16 14:47 UTC, brickspert commented on packages/hooks/src/useEventTarget/index.ts
> +    if (typeof transformer === 'function') {
transformer 可以用 usePersistFn 持久化一下再用。

现在这样会出现问题：如果 transformer 变化了，或者依赖了其它的 state，这里都不能感知到。

2020-03-16 14:47 UTC, brickspert commented on packages/hooks/src/useEventTarget/index.en-US.md
> +const [ { value, onChange }, reset ] = useEventTarget<T>(initialValue: T, transformer?: T => T );
initialValue?: T

2020-03-16 14:47 UTC, n0ruSh commented on packages/hooks/src/useEventTarget/index.ts
> +export default <T>(initialValue: T, transformer?: (value: T) => T): [
> value 和 onChange 不一定非要一起用。比如
> 
> ```
> const [{value, onChange}] = useEventTarget('',  (t)=>!!t );
> 
> <Input onChange={onChange} />
> <div>{value}</div>
> ```

好吧。。￣□￣｜｜

2020-03-17 01:46 UTC, brickspert commented on packages/hooks/src/useEventTarget/index.ts
> +  const persistTransformer = transformer == null ? transformer : usePersistFn(transformer);
hooks 不能在判断条件里面用，会出问题。

如果 transformer 可能是 null 的话，这样写

```
consnt transformerRef = useRef(transformer);
transformerRef.current = transformer;
```

2020-03-17 14:14 UTC, brickspert approved these changes
LGTM

2020-03-17 14:20 UTC, ttys026 approved these changes
legit

2020-03-18 01:46 UTC, merged