Feat/use text selection
alibaba/hooks pull request #312
Opened 2020-03-21 09:54 UTC by chenjsh36

RFC Issue #309 实现

2020-03-21 10:49 UTC, ttys026 requested changes

2020-03-21 10:49 UTC, tli4 commented on packages/hooks/src/useTextSelection/index.ts
> +      console.log('mouse up:', window.getSelection);
console.log need to remove

2020-03-21 10:49 UTC, tli4 commented on packages/hooks/src/useTextSelection/index.ts
> +    console.log('on textselection useeffect xxxx');
console.log need to remove

2020-03-21 11:25 UTC, brickspert commented on packages/hooks/src/useTextSelection/index.ts
> +import React, { useState, useEffect } from "react";
unused React

2020-03-21 11:25 UTC, brickspert commented on packages/hooks/src/useTextSelection/index.ts
> +  throw Error('"element" 参数格式不合法， 请传入对应 string 或 HTMLElement');
应该写英语

2020-03-21 11:25 UTC, brickspert commented on packages/hooks/src/useTextSelection/index.ts
> +  const range = selection.getRangeAt(0);
比较好奇如果 range 是换行的，这里读取到的是正确的吗。似乎值是对的，不过展示效果不是很好。有没有好的解决办法。

![image](https://user-images.githubusercontent.com/12526493/77224940-5e0e6900-6ba5-11ea-95af-d13d3129f5b6.png)

2020-03-21 11:25 UTC, brickspert commented on packages/hooks/src/useTextSelection/index.ts
> +    console.log('on textselection useeffect xxxx');
啊哈~~

2020-03-21 11:25 UTC, brickspert commented on packages/hooks/src/useTextSelection/index.ts
> +export default (element: IProps = initProps) => {
建议 element 与 useScroll/useSize 等 Hooks 的 dom 保持一致。

包括类型，以及如果没有传 element，可以返回一个 `ref` 让用户使用。

2020-03-21 11:25 UTC, brickspert commented on packages/hooks/src/useTextSelection/index.ts
> +      console.log('mouse up:', window.getSelection);
建议不要 console.log

2020-03-21 11:25 UTC, brickspert commented on packages/hooks/src/useTextSelection/index.zh-CN.md
> +  title: Dom
建议放到 UI 分类下。

2020-03-21 11:25 UTC, brickspert commented on packages/hooks/src/useTextSelection/index.zh-CN.md
> +实时获取用户当前选取的文本范围。
实时获取用户当前选取的文本内容及位置。

2020-03-21 11:25 UTC, brickspert commented on packages/hooks/src/useTextSelection/index.zh-CN.md
> +  text: string;
不全

2020-03-21 11:25 UTC, brickspert commented on packages/hooks/src/useTextSelection/demo/demo1.tsx
> +  const selection = useTextSelection();
![image](https://user-images.githubusercontent.com/12526493/77225204-08878b80-6ba8-11ea-9516-5ea3726067a1.png)

不选择 text，直接随便点击， position 会变化，这是预期行为吗？

2020-03-21 11:25 UTC, brickspert commented on packages/hooks/src/useTextSelection/demo/demo1.tsx
> +        请滑动你的鼠标在页面上随意选取文本~~~~~
demo 全部使用英文。下同~

2020-03-21 11:25 UTC, brickspert commented on packages/hooks/src/useTextSelection/demo/demo3.tsx
> +let reqId  = 0; // 最新请求 ID
esling 感觉不对劲。多个空格，另外 useLayoutEffect 好像也没用。

2020-03-21 11:25 UTC, brickspert commented on packages/hooks/src/useTextSelection/demo/demo3.tsx
> +  useEffect(() => {
这一块建议直接用 useRequest 发起请求。 loading、result、resultPosition 应该都可以不要。
通过 loading 与 data 应该可以直接判断。

```

const getTranslateResult = ()=>{
   const trimedText = text.trim() === '';
   if(!trimedText) { return Promise.resolve('') };
   return new Promise(resolve => {
        setTimeout(() => resolve(`【翻译结果】${keyword}`), 2000);
    })
}

const {data, loading} = useRequest(getTranslateResult, {
    manual: true,
    refreshDeps: [text]
});
```

2020-03-21 13:59 UTC, chenjsh36 commented on packages/hooks/src/useTextSelection/demo/demo1.tsx
> +  const selection = useTextSelection();
预期行为，随便点击等于选取空文本，也相当于一次文本选取的过程。

2020-03-29 16:38 UTC, chenjsh36 commented on packages/hooks/src/useTextSelection/index.ts
> +  const range = selection.getRangeAt(0);
我看了下 antd 的 popover 在换行情况下的交互，发现确实是这样的设计。

2020-03-29 16:38 UTC, chenjsh36 commented on packages/hooks/src/useTextSelection/index.ts
> +export default (element: IProps = initProps) => {
以保持一致

2020-03-31 02:34 UTC, brickspert approved these changes
LGTM

2020-03-31 02:38 UTC, ttys026 approved these changes

2020-03-31 02:39 UTC, merged