Feat/use sortable
alibaba/hooks pull request #316
Opened 2020-03-23 15:30 UTC by tli4

2020-03-25 03:07 UTC, awmleer reviewed
还需要在 `index.ts` 中 export 一下？

2020-03-25 03:07 UTC, awmleer commented on packages/hooks/src/useSortable/demo/demo1.tsx
> +      <div style={{ border: '1px solid #e8e8e8', height: 66, padding: 8, margin: 8, lineHeight: '50px' }} {...getSortProps(i)} >
有没有可能把 `props` 也放到 `list` 中。。？这样就可以更简化了：
```suggestion
      <div style={{ border: '1px solid #e8e8e8', height: 66, padding: 8, margin: 8, lineHeight: '50px' }} {ele.props} >
```

2020-03-25 03:07 UTC, awmleer commented on packages/hooks/src/useSortable/index.en-US.md
> +const { getSortProps, list, dragging } = useSortable<T>({
`dragging` 是啥呀。。后面 API 里好像没有这个字段

2020-03-25 13:23 UTC, tli4 commented on packages/hooks/src/useSortable/index.en-US.md
> +const { getSortProps, list, dragging } = useSortable<T>({
去掉了

2020-03-26 02:43 UTC, awmleer commented on packages/hooks/src/useSortable/index.zh-CN.md
> +| list  | 完整的待排序列表 | { type: 'dummy' \| 'item', content: T, props: PropsType }[] |
既然只有一个字段了。。是不是都不用包裹成 object 了
或者说，为了考虑后面的可拓展性还是保留 object 的这种形式比较好？

2020-03-26 15:54 UTC, brickspert commented on packages/hooks/src/useSortable/demo/demo1.tsx
> +import React, { useState } from 'react';
unused useState

感觉你的 eslint 没开起来~~

2020-03-26 15:54 UTC, brickspert commented on packages/hooks/src/useSortable/index.zh-CN.md
> +| list  | 完整的待排序列表 | { type: 'dummy' \| 'item', content: T, props: PropsType }[] |
我觉得可以加上 setList 的能力。
就可以实现，边加边排序，边删边排序等。这个都是刚需感觉。

2020-03-26 15:54 UTC, brickspert commented on packages/hooks/src/useSortable/index.zh-CN.md
> +| list  | 完整的待排序列表 | { type: 'dummy' \| 'item', content: T, props: PropsType }[] |
const [list , setList] = useSortable(initialList)

2020-03-26 15:54 UTC, brickspert commented on packages/hooks/src/useSortable/index.ts
> +      key: JSON.stringify(list[index]),
JSON.stringify 的性能贼烂，并且也不能保证一定都不一样。

可以换个吗？或者让用户设置 key，我们就不管这个 key 了。你觉得呢~~

2020-03-26 15:54 UTC, brickspert commented on packages/hooks/src/useSortable/index.ts
> +          setList(lastSorted.current.slice(0, index).concat({ type: 'dummy', content: 'dummy' as any as T }).concat(lastSorted.current.slice(index)));
两个 setList 一模一样？

2020-03-27 09:23 UTC, tli4 commented on packages/hooks/src/useSortable/index.ts
> +      key: JSON.stringify(list[index]),
用户如果用 index 做 key 会有问题，这里比较 tricky 的，感觉最好还是包掉。因为插入 dummy 节点，后面的 key 如果用了 index 会乱掉

2020-03-27 11:27 UTC, awmleer commented on packages/hooks/src/useSortable/index.ts
> +      key: JSON.stringify(list[index]),
为什么不让用户自己设置 `key` 呢。。

2020-03-27 11:29 UTC, brickspert commented on packages/hooks/src/useSortable/index.ts
> +      key: JSON.stringify(list[index]),
JSON.stringify 可能重复，如果用户 list 数据一致的话。

2020-03-29 04:30 UTC, brickspert requested changes

2020-03-29 04:30 UTC, brickspert commented on packages/hooks/src/useSortable/index.ts
> +    setList
现在的 setList 感觉不好用。

我如果想用 setList，我需要自己 list.map 过滤出真实的数据，再去 setList，太麻烦了 ~

是不是除了 list 外，再返回一个原生格式的 list，供用户增删改查？名字可以另外起~

2020-03-29 04:31 UTC, brickspert commented
是不是可以加上 禁用某条数据的移动，也比较常见。

2020-04-07 05:28 UTC, tli4 commented on packages/hooks/src/useSortable/index.ts
> +    setList
支持 setList(newList) 和 setList((oldList)=> newList ) 两种用法了

2020-04-07 05:29 UTC, tli4 commented on packages/hooks/src/useSortable/index.ts
> +      key: JSON.stringify(list[index]),
去掉了 key，交给用户自己处理

2020-04-07 05:30 UTC, tli4 commented
> 是不是可以加上 禁用某条数据的移动，也比较常见。

增加了 disabledItems 配置，`(ele: T) => boolean;`

2020-06-18 03:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/hooks?pullRequest=316) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/hooks?pullRequest=316) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: brickspert<br/>:x: troy.lty<br/><hr/>**troy.lty** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/hooks?pullRequest=316) it.</sub>

2020-06-22 04:08 UTC, awmleer commented on packages/hooks/src/useSortable/index.zh-CN.md
> +| setList  | 更新 list 的值 | T[] \| ((oldList: T[]) => T[]) |
上面 API 部分写错了吧。。应该是 `[list, setList]`

2020-07-08 07:32 UTC, closed without merging