feat: useUrlState
alibaba/hooks pull request #446
Opened 2020-06-22 05:09 UTC by tli4

2020-06-22 09:46 UTC, awmleer reviewed
这个是只能单向把 `state` 同步到 URL 上么。。如果 URL 变化的话好像并不能同步更新 state？

2020-06-22 09:46 UTC, awmleer commented on packages/hooks/src/useUrlState/index.zh-CN.md
> +提供虚拟化列表能力的 Hook，用于解决展示海量数据渲染时首屏渲染缓慢和滚动卡顿问题。
文档好像不对。。

2020-06-22 13:22 UTC, brickspert commented
关于 `useUrlState` 我想探讨下。我在业务中有写类似的 Hooks，我的需求是这样的：“在 Url 上记录分页信息 current、pageSize”。

1. 希望 `useUrlState` 能接收一个 object，管理多个字段。
2. 希望 `useUrlState` 能监听 url 的变化，并触发组件渲染。比如点击浏览器后退，current/pageSize 变化。
3. 根据第二点，我认为是 `replace` 还是 `push` 也是有争议的。

这是我的用法

```ts
  const [state, setState] = useUrlState<UrlState>({
    current: 1,
    pageSize: 10,
    range: 'MY',
    keyword: '',
    status: '',
  });

  setState({ keyword: 'aa' });
```

这是我的实现

```ts
import { history } from 'umi';
import { useCallback, useEffect, useState } from 'react';
import { usePersistFn } from 'ahooks';

const useUrlState = <T extends Object>(defaultState: T) => {
  const mergeQueryAndDefault = usePersistFn((query: Object) => {
    const tempState: any = {};
    Object.keys(defaultState).forEach(k => {
      if (k in query) {
        tempState[k] = query[k];
      } else {
        tempState[k] = defaultState[k];
      }
    });
    return tempState;
  });

  const [state, setState] = useState<T>(() => {
    return mergeQueryAndDefault(history.location.query);
  });

  useEffect(() => {
    return history.listen((location: any) => {
      setState(mergeQueryAndDefault(location.query));
    });
  }, [mergeQueryAndDefault]);

  const setUrlState = useCallback((states: Partial<T>) => {
    history.push({
      query: {
        ...history.location.query,
        ...states,
      },
    });
  }, []);

  return [state, setUrlState] as const;
};

export default useUrlState;

```

2020-06-22 13:40 UTC, tli4 commented
> 希望 useUrlState 能接收一个 object，管理多个字段。

这个问题我也考虑了，其实接受 object 和接受 (key, state) 的方式是冲突的。两种都有适用的场景。可能 API 还需要再讨论一下，要加一些配置项了。

> 希望 useUrlState 能监听 url 的变化，并触发组件渲染。比如点击浏览器后退，current/pageSize 变化

这也是一个合理的场景，replace 和 push 可能也要变成配置，比如 drawerVisible 这种 state 可能是希望 replace，pageNum 应该是 push

监听方面，没有 umi 暴露的 history，自己处理会麻烦一些，需要复写 pushState, replaceState, popState。这块先搞一个 RFC 我们一起 review 下再改吧

2020-06-23 02:14 UTC, awmleer commented
> 监听方面，没有 umi 暴露的 history，自己处理会麻烦一些，需要复写 pushState, replaceState, popState。这块先搞一个 RFC 我们一起 review 下再改吧

我觉得不应该是由这个 Hook 去做监听的事情，而是应该让外面在调用这个 Hook 的时候把 query 作为参数传递进来，这样就只需要一个 useEffect 就能解决问题了

2020-06-28 03:35 UTC, jeasonstudio commented
> 这个是只能单向把 `state` 同步到 URL 上么。。如果 URL 变化的话好像并不能同步更新 state？

@tli4 @brickspert 

`useUrlState` 本身算是一个不太 Hooks 的用法：
1. 对于 URL state 来说是多组件公用的，没有 `useState` 状态在组件间的隔离，所以如果支持 url 同步更新触发组件 rerender 大概率会导致问题。
2. `useUrlState` 应该更向着 `useSessionStorage/useLocalStoarge` 靠拢，它们属于一类 hook
3. 为了解决 quote 的问题，我们可以提供类似 `useUrlParamsEffect` 的监听类 Hook
4. 是否同时支持 BrwoserHistory/HashHistory 的 UrlParams

```js
useUrlParamsEffect(() => { /* do something */ }, ['currentPage', 'pageSize']);
```

2020-06-29 15:01 UTC, chenbin92 commented on packages/hooks/src/useUrlState/index.zh-CN.md
> +const [ state, setState ] = useUrlState(key, initialState);
`[ state, setState ] ` 前后不需要空格 ？

2020-07-06 13:08 UTC, brickspert commented
useUrlState 可以出个 RFC

2020-07-26 02:47 UTC, brickspert requested changes
下面两个图的逻辑应该都不对吧。
![image](https://user-images.githubusercontent.com/12526493/88470265-01450580-cf2d-11ea-88e9-d0148bec3425.png)

![image](https://user-images.githubusercontent.com/12526493/88470295-56811700-cf2d-11ea-8a8e-0c706f78232e.png)

2020-07-26 02:47 UTC, brickspert commented on packages/hooks/src/useUrlState/index.zh-CN.md
> +| setState     | 同 useState                             |  (state: S) => void \| (() => ((state: S) => S))      |
setState 应该不是同 useState 吧？
而是同 useSetState？这里可以给下示例和解释

2020-07-26 02:47 UTC, brickspert commented on packages/hooks/src/useUrlState/index.ts
> +        getter: (url: string) => S;
getter 和 setter 是不准备体现在文档上了吗？

2020-07-26 02:47 UTC, brickspert commented on packages/hooks/src/useUrlState/index.ts
> +      _setState(nextState);
这个 _setState 应该是不需要的，url 变化后，useEffect 里面已经监听，并变化了 state

2020-07-26 02:47 UTC, brickspert commented on packages/hooks/src/useUrlState/demo/demo1.tsx
> +      <button type="button" onClick={() => setState({ count: undefined })}>
button 中间加个 margin

2020-07-26 02:47 UTC, brickspert commented on packages/hooks/src/useUrlState/index.ts
> +  parseBooleans: true,
建议 parseNumbers / parseBooleans / skipEmptyString 都不要，否则会给用户造成困扰。
比如我就是想用 `"123"` ，但是你给我转成了 `123`，不如不做转换，全部用字符串。

2020-07-27 06:27 UTC, tli4 commented on packages/hooks/src/useUrlState/index.zh-CN.md
> +| setState     | 同 useState                             |  (state: S) => void \| (() => ((state: S) => S))      |
这里我觉得用 useSetState 的模式，限制的有些死了，follow 官网的 useState 还有办法可以实现 useSetState 的模式，但是如果在组件库里就切成 useSetState，没有办法完整覆盖 state 了

2020-07-27 06:35 UTC, tli4 commented
@brickspert 图里的两个也是故意这样设计的，包括测试用例里其实就有这个场景。我理解是不能把 state 完整覆盖到 url 上的。如果这样互相覆盖，那一个页面内不能出现两个 useUrlState 了，另外很多场景会把一些通用信息写到 query 里，例如 `language=zh-CN`，`temperature=fahrenheit`，不希望这些属性被覆盖调而是 append 把

2020-07-27 06:47 UTC, tli4 commented on packages/hooks/src/useUrlState/index.ts
> +  parseBooleans: true,
skipEmptyString 感觉还是需要的，想不到什么场景需要把一个 `queryName=` 这样的 query 挂在 url 上

2020-07-27 09:23 UTC, tli4 commented on packages/hooks/src/useUrlState/index.ts
> +      _setState(nextState);
从 initialState set 成 undefined，url 不会变化，但是 state 需要变化

2020-07-30 08:57 UTC, jeasonstudio commented on packages/hooks/src/useUrlState/index.ts
> +import { stringify, parse } from 'query-string';
[https://www.npmtrends.com/qs-vs-query-string-vs-querystring-vs-querystringify-vs-urijs-vs-url-parse](https://www.npmtrends.com/qs-vs-query-string-vs-querystring-vs-querystringify-vs-urijs-vs-url-parse)

从受欢迎度和下载量来看 `qs` 比 `query-string` 更有优势一些，可以考虑下是否替换。

![image](https://user-images.githubusercontent.com/17971291/88897074-4d6dae00-d27d-11ea-85f9-85d03c9ae954.png)

2020-07-30 08:57 UTC, jeasonstudio commented on packages/hooks/src/useUrlState/index.ts
> +  const configRef = useRef({ historyType, navigateMode });
这里组件 rerender 时，我们对 config 的变化做响应吗:
```jsx
export function MyComponent() {
  const [type, setType] = useState('browser');
  const [state] = useUrlState({});
  return <button onClick={() => setType('hash')}>switch</button>;
}
```

2020-07-30 08:57 UTC, jeasonstudio commented on packages/hooks/src/useUrlState/index.ts
> +      };
监听 history 上 state 变化建议通过监听事件来实现：
```jsx
// 全局重写 `history.pushState` 和 `history.replaceState`，目的是增加 window 上的事件，这里略
history.pushState = ...;
history.replaceState = ...;

// 在 hook 的声明周期中添加/移除事件 callback
useEffect(() => {
  const updateUrl = () => {
    // xxx
  };
  window.addEventListener("pushState", updateUrl);
  window.addEventListener("replaceState", updateUrl);
  return () => {
    window.removeEventListener("pushState", updateUrl);
    window.removeEventListener("replaceState", updateUrl);
  };
}, []);
```

目前的写法也会会导致套娃问题，带来过多的闭包变量，当前 `useEffect` 中解构取到的 `replaceState` 方法，或许已经被其他组件中的 `useUrlState` 改造过了，但通过事件可以有效避免这一问题，一个 event 上挂载各自组件的 callback。

2020-07-30 08:57 UTC, jeasonstudio commented on packages/hooks/src/useUrlState/index.ts
> +      };
一个添加事件的参考代码，来自网络：
```ts
const override = function(type: string) {
  const func = history[type] as (
    data: any,
    title: string,
    url?: string
  ) => void;
  return function() {
    const rv = func.apply(this, arguments) as any;
    const e = new Event(type) as any;
    e.arguments = arguments;
    window.dispatchEvent(e);
    return rv;
  };
};
history.pushState = override("pushState");
history.replaceState = override("replaceState");
```

2020-07-30 08:57 UTC, jeasonstudio commented on packages/hooks/src/useUrlState/index.ts
> +          configRef.current.historyType.getter
这三个判断条件可以简化成
```ts
if (configRef.current?.historyType?.getter) {}
```

2020-07-30 08:57 UTC, jeasonstudio commented on packages/hooks/src/useUrlState/index.ts
> +          const [query] = rawQuery.split('#');
通过 split 是否没有考虑一些特殊情况，比如同时包含 browser/hash qs，qs value 中包含未 encode 的 `?`，比如：
* `https://example.com/foo?a=1#/bar?b=2?&c=3`

2020-07-30 08:57 UTC, jeasonstudio commented on packages/hooks/src/useUrlState/index.ts
> +      const [query] = rawQuery.split('#');
同理

2020-07-30 08:57 UTC, jeasonstudio commented on packages/hooks/src/useUrlState/index.ts
> +  const lastUrl = useRef('');
这里缓存 lastUrl 的目的是？后面跟 lastUrl 有关的判断逻辑直接换成 location.href 会导致问题么？

2020-08-03 06:45 UTC, tli4 commented
和 @brickspert @awmleer 讨论之后，应该要采用依赖 react-router 的方式重写。 @jeasonstudio 辛苦上面的 review 了🙏 我这周抽时间重写

2020-08-03 06:53 UTC, jeasonstudio commented
> 和 @brickspert @awmleer 讨论之后，应该要采用依赖 react-router 的方式重写。 @jeasonstudio 辛苦上面的 review 了🙏 我这周抽时间重写

如果用 `reach-router` 不支持么，同时 `react-router` 比较坑，每两个大版本就有一次重构性的改动，比如 v3->v4，以及马上的 v6，我们耦合 `react-router` 是面向哪个版本呢。 @tli4

2020-08-03 07:48 UTC, tli4 commented
> > 和 @brickspert @awmleer 讨论之后，应该要采用依赖 react-router 的方式重写。 @jeasonstudio 辛苦上面的 review 了🙏 我这周抽时间重写
> 
> 如果用 `reach-router` 不支持么，同时 `react-router` 比较坑，每两个大版本就有一次重构性的改动，比如 v3->v4，以及马上的 v6，我们耦合 `react-router` 是面向哪个版本呢。 @tli4

之前讨论的是依赖 v5; v6 的 useLocation 和 useHistory 的 hook 应该没有 break change。这样搞的目的主要是内部的微前端场景。会动态修改路由类型。比如子应用里原本的 useUrlState 可能并不希望作用于外层应用的 location 上。如果自己实现的 history 监听其实是没法判断 history 什么时候从 browser/hash 变成 memory 的

2020-08-03 07:59 UTC, tli4 commented on packages/hooks/src/useUrlState/index.ts
> +          const [query] = rawQuery.split('#');
根据 [RFC3986 ](https://tools.ietf.org/html/rfc3986#section-4.2)
relative-part [ "?" query ] [ "#" fragment ]
如果是这种不符合标准的 url，应该不用支持，多余的 ?,# 应该都需要 encode

2020-08-07 11:08 UTC, awmleer requested changes

2020-08-07 11:08 UTC, awmleer commented on packages/hooks/src/useUrlState/index.ts
> +      ...parse(routerLocation.search, parseConfig),
`parse` 这里是不是应该 `useMemo` 一下？

2020-08-07 11:08 UTC, awmleer commented on packages/hooks/src/useUrlState/index.ts
> +        search: stringify({ ...initialState.current, ...newState }, parseConfig) || '?',
为啥还需要 `|| ?` 啊，直接空字符的话，url 可能会更干净一些？

2020-08-07 11:08 UTC, awmleer commented on packages/hooks/src/useUrlState/index.ts
> +          delete initialState.current[k];
这里如果不 delete 的话，下面 `stringify` 的时候，应该也会自动去掉这个字段的

2020-08-07 11:08 UTC, awmleer commented on packages/hooks/src/useUrlState/index.ts
> +  locationFn.current = routerLocation;
这样 `ref` 的话，后面 current mode 是不是会挂。。？

2020-08-07 11:08 UTC, awmleer commented on packages/hooks/src/useUrlState/index.ts
> +export default <S extends Record<string, any> = Record<string, any>>(
其实更准确一些的类型定义应该是类似 `qs` 里这样的。。

```ts
interface ParsedQs { [key: string]: undefined | string | string[] | ParsedQs | ParsedQs[] }
```

2020-08-07 11:08 UTC, awmleer commented on packages/hooks/src/useUrlState/index.ts
> +  const initialState = useRef(typeof value === 'function' ? (value as () => S)() : value || {});
感觉不是 `initialState` 而应该是 `defaultValue`？是用来用默认参数补齐 url 中缺失的参数的，而不是**初始**值

2020-08-10 06:52 UTC, tli4 commented on packages/hooks/src/useUrlState/index.ts
> +        search: stringify({ ...initialState.current, ...newState }, parseConfig) || '?',
这里直接空字符串会有问题的, setState({ key: undefined }) 的时候，如果是空字符串没办法覆盖默认值

2020-08-10 07:09 UTC, tli4 commented on packages/hooks/src/useUrlState/index.ts
> +          delete initialState.current[k];
是会自动去掉，但是再下次 setState 的时候，如果 state 里没有这一个 key，那对应的值就变成了 initialState，
但其实这里期望的是 undefined.

2020-08-10 07:11 UTC, tli4 commented on packages/hooks/src/useUrlState/index.ts
> +  locationFn.current = routerLocation;
concurrent mode 下会挂的东西比较多，因为官方的 setState 实例其实是永远不变的，如果把 location 和 history 的值都加到 deps 里，那这个 setState 会一直在变

2020-08-10 07:15 UTC, tli4 commented on packages/hooks/src/useUrlState/index.ts
> +      ...parse(routerLocation.search, parseConfig),
这里的 parse 只用了一次，感觉不需要 useMemo。
（setState callback 里的是用的 ref 拿到最新的值，如果 memo 了，deps 里又要加一个额外的依赖）

2020-08-10 07:51 UTC, brickspert commented on packages/hooks/src/useUrlState/index.ts
> +      ...parse(routerLocation.search, parseConfig),
我也感觉需要 useMemo 下，parse 应该只在 routerLocation.search 变化的时候才执行一次。

2020-08-12 12:14 UTC, awmleer commented on packages/hooks/src/useUrlState/index.ts
> +          delete initialState.current[k];
这里我觉得就应该重置会默认值啊，而不应该是 `undefined`，因为 url state 应该确保在刷新页面也保持一致，现在这样做的话，就不一致了

2020-08-12 12:45 UTC, awmleer commented on packages/hooks/src/useUrlState/index.ts
> +  locationFn.current = routerLocation;
OK～

2020-08-12 13:11 UTC, brickspert approved these changes

2020-08-13 15:02 UTC, merged

2020-11-27 01:18 UTC, petitspois commented
parseConfig 为什么不能变成可配置呢