feat: useCookieState
alibaba/hooks pull request #462
Opened 2020-06-29 10:09 UTC by Straw94

### API
```javascript
interface IOptions<T = any> {
  defaultValue?: T | (previousState?: T) => T;
  timestamp?: number;
  path?: string;
  expires?: Date;
}

const [state, setState] = useCookieState<T>(
  key: string,
  options?: IOptions,
): [T | undefined, (value?: T | (previousState?: T) => T) => void]
```
### DEMO
```javascript
import React from 'react';
import useCookieState, { IOptions } from '../index';

export default function () {
  const options: IOptions<string> = {
    defaultValue: 'Hello',
  };
  const [message, setMessage] = useCookieState<string>('user-message', options);
  return (
    <>
      <input
        value={message || ''}
        placeholder="Please enter some words..."
        onChange={(e) => setMessage(e.target.value)}
      />
      <button style={{ margin: '0 16px' }} type="button" onClick={() => setMessage('Hello~')}>
        Set Hello
      </button>
      <button type="button" onClick={() => setMessage()}>
        clear
      </button>
    </>
  );
}

```

2020-06-29 10:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/hooks?pullRequest=462) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/hooks?pullRequest=462) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: brickspert<br/>:white_check_mark: awmleer<br/>:x: 稻草<br/><hr/>**稻草** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/hooks?pullRequest=462) it.</sub>

2020-06-29 11:20 UTC, Straw94 commented
+1

2020-06-29 12:20 UTC, brickspert commented
为什么不用 `js-cookie` 库呢？自己实现不太好。

另外，我感觉直接参考 react-use 貌似就挺好的，只有几行代码：https://github.com/streamich/react-use/blob/master/src/useCookie.ts

2020-06-29 12:23 UTC, brickspert commented on packages/hooks/src/useCookieState/demo/demo2.tsx
> + * desc.zh-CN: useLocalStorageState 会自动处理序列化和反序列化的操作。
`useLocalStorageState` ?

2020-06-29 12:23 UTC, brickspert commented
另外就是建议不要再自动做 `JSON.stringify()` 了，坑很多，用户需要的话，自己手动处理下。

cc @awmleer

2020-06-30 02:23 UTC, Straw94 commented
> 为什么不用 `js-cookie` 库呢？自己实现不太好。
> 
> 另外，我感觉直接参考 react-use 貌似就挺好的，只有几行代码：https://github.com/streamich/react-use/blob/master/src/useCookie.ts

好的，学习下～

2020-06-30 15:32 UTC, brickspert commented on packages/hooks/src/useCookieState/index.en-US.md
> +<code src="./demo/demo2.tsx" />
应该需要提供一个使用 options 的例子

2020-06-30 15:32 UTC, brickspert commented on packages/hooks/src/useCookieState/index.en-US.md
> +  (newValue?: string | ((prevState: string) => string), options?: Cookies.CookieAttributes) => void,
Cookies.CookieAttributes 应该要列一下吧，要不不知道有哪些属性。

2020-06-30 15:32 UTC, brickspert commented on packages/hooks/src/useCookieState/index.zh-CN.md
> +legacy: /zh-CN/state/use-cookie-state
legacy 是不要的。这是历史栈，新的 Hooks 都不用设置这个

2020-06-30 15:32 UTC, brickspert commented on packages/hooks/src/useCookieState/index.ts
> +        const currentState = newValue(Cookies.get(cookieKey) || getDefaultValue());
这里不应该再去读 getDefaultValue 了，这一段建议这么写


```js
        setState((prevState) => {
          const currentState = newValue(prevState);
          if (newValue === undefined || newValue === null) {
             Cookies.remove(cookieKey);
          }else{
              Cookies.set(cookieKey, currentState, cookieOptions);
          }
          return currentState;
        });
```

2020-06-30 15:32 UTC, brickspert commented on packages/hooks/src/useCookieState/demo/demo2.tsx
> +import React from 'react';
demo2 太复杂了，搞一个自增的 count 就挺好。一个数字，一个 button 就说明问题了。

2020-06-30 15:32 UTC, brickspert commented on packages/hooks/src/useCookieState/index.ts
> +        setState(null);
```suggestion
        setState(newValue);
```

2020-06-30 15:32 UTC, brickspert commented on packages/hooks/src/useCookieState/index.ts
> +      newValue?: string | ((prevState: string) => string | null),
```suggestion
      newValue?: string | ((prevState: string) => string | null | undefined),
```

2020-06-30 15:37 UTC, brickspert commented on packages/hooks/src/useCookieState/index.ts
> +    if (cookieValue) return cookieValue;
如果 cookieValue 是空字符串，这里会有问题吧？

应该是 `if(cookieValue !== undefined) return cookieValue`;

2020-07-01 01:45 UTC, Straw94 commented on packages/hooks/src/useCookieState/index.ts
> +        const currentState = newValue(Cookies.get(cookieKey) || getDefaultValue());
这个位置不读取defaultValue的话，设置默认值后，首次使用function updater，获取不到state值吧

2020-07-01 01:47 UTC, brickspert commented on packages/hooks/src/useCookieState/index.ts
> +        const currentState = newValue(Cookies.get(cookieKey) || getDefaultValue());
能获取到的~

你现在的写法其实有问题的，比如 cookie 为 空字符串，那就变成默认值了。

2020-07-01 13:18 UTC, brickspert commented on packages/hooks/src/useCookieState/demo/demo3.tsx
> + * desc: function updater is also acceptable with useCookieState.
demo 3 和 demo 2 完全一样了

2020-07-01 13:18 UTC, brickspert commented on packages/hooks/src/useCookieState/index.zh-CN.md
> +   * Define when the cookie will be removed. Value can be a Number
中文？或者直接用 table 来描述 options 吧。这样和其它文档不一样了。

2020-07-01 13:18 UTC, brickspert commented on packages/hooks/src/useCookieState/demo/demo1.tsx
> +import useCookieState, { IOptions } from 'ahooks/lib/useCookieState';
引用地址不对。这里其实不用用 IOptions。

使用的地方不用单独定义 options 就好了。

2020-07-01 13:18 UTC, brickspert commented on packages/hooks/src/useCookieState/index.ts
> +          if (newValue === undefined || newValue === null) {
```suggestion
          if (value === undefined || value === null) {
```

2020-07-01 13:18 UTC, brickspert commented on packages/hooks/src/useCookieState/index.ts
> +    if (cookieValue) return cookieValue;
同上

2020-07-22 04:58 UTC, awmleer requested changes

2020-07-22 04:58 UTC, awmleer commented on .umirc.js
> +  // ssr: {},
为啥要把 ssr 关掉。。？

2020-07-22 04:58 UTC, awmleer commented on packages/hooks/package.json
> +    "@types/js-cookie": "^2.2.6",
types 也应该放到 dependencies 里吧

2020-07-22 04:58 UTC, awmleer commented on packages/hooks/src/useCookieState/index.ts
> +  return [state, updateState];
```suggestion
  return [state, updateState] as const;
```

这里可以 as const 的，这样上面就不用手动标函数的返回类型了

2020-07-22 04:58 UTC, awmleer commented on packages/hooks/src/useCookieState/index.ts
> +          if (value === undefined || value === null) {
这里 `value` 如果支持 `null` 的话，上面 `CookieState` 的类型定义是不是也需要补上 `| null`？

2020-07-22 04:58 UTC, awmleer commented on packages/hooks/src/useCookieState/index.ts
> +      updateOption: Cookies.CookieAttributes = {},
是否有必要支持 `updateOption`。。？

2020-07-22 04:58 UTC, awmleer commented on packages/hooks/src/useCookieState/index.ts
> +      updateOption: Cookies.CookieAttributes = {},
现在这样的实现可能会导致 bug：

```js
const [x, setX] = useCookieState('x', {secure: true})
setX('a', {secure: false})
// 此时浏览器的 cookie 中 secure 被置为 false 了
setX('b')
// 此时浏览器的 cookie 中 secure 被重置为 true 了
```

2020-07-22 04:58 UTC, awmleer commented on packages/hooks/src/useCookieState/index.ts
> +  }
`getDefaultValue` 这个函数为啥不直接 inline 掉呢。。只有这一处使用
这样就可以直接用 ts 的类型推导了
```suggestion
  const [state, setState] = useState(() => {
  const cookieValue = Cookies.get(cookieKey);
    if (cookieValue !== undefined) return cookieValue;
    if (isFunction(options.defaultValue)) return options.defaultValue();
    return options.defaultValue;
  });
```

2020-07-22 07:38 UTC, Straw94 commented on packages/hooks/src/useCookieState/index.ts
> +  }
👌

2020-07-22 07:39 UTC, Straw94 commented on packages/hooks/src/useCookieState/index.ts
> +          if (value === undefined || value === null) {
CookieState 的类型定义有 null

2020-07-22 07:40 UTC, Straw94 commented on packages/hooks/package.json
> +    "@types/js-cookie": "^2.2.6",
OK

2020-07-22 07:40 UTC, Straw94 commented on packages/hooks/src/useCookieState/index.ts
> +  return [state, updateState];
学到了

2020-07-22 07:40 UTC, Straw94 commented on .umirc.js
> +  // ssr: {},
这个好像是工程修改的吧，没有调整过这个

2020-07-22 07:42 UTC, awmleer commented on .umirc.js
> +  // ssr: {},
OK～

2020-07-22 07:44 UTC, Straw94 commented on packages/hooks/src/useCookieState/index.ts
> +      updateOption: Cookies.CookieAttributes = {},
这个不算是 BUG 吧，只能说如果不设置 options ，会有默认属性

2020-07-22 07:45 UTC, brickspert commented on packages/hooks/src/useCookieState/index.ts
> +      updateOption: Cookies.CookieAttributes = {},
这个应该没有问题吧。

目前实现是，如果 update 时没有设置 options，则使用之前的 options。会做一次 merge 的

2020-07-22 08:21 UTC, awmleer commented on packages/hooks/src/useCookieState/index.ts
> +      updateOption: Cookies.CookieAttributes = {},
和 @brickspert 确认了一下。。这样应该是预期行为

2020-07-22 09:39 UTC, Straw94 commented on packages/hooks/src/useCookieState/index.ts
> +    if (cookieValue) return cookieValue;
不需要处理空字符串吧，空字符串应该是作为一个值来存储使用的

2020-07-22 09:44 UTC, awmleer commented on packages/hooks/package.json
> +    "@types/js-cookie": "^2.2.6",
都放到上面了。。这里就可以删掉了。。
```suggestion
```

2020-07-23 10:39 UTC, awmleer approved these changes

2020-07-23 12:13 UTC, awmleer commented on packages/hooks/src/useCookieState/index.ts
> +      newOptions?: Cookies.CookieAttributes,
@brickspert 那这里是不是也可以 `={}`，这样下面就不用 `|| {}` 了，这样就和外层的 `useCookieState` 保持一致了

2020-07-23 12:29 UTC, merged