Feat/use interval
alibaba/hooks pull request #470
Opened 2020-07-01 09:47 UTC by Qkxinq

2020-07-01 09:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/hooks?pullRequest=470) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/hooks?pullRequest=470) before we can accept your contribution.<br/><hr/>**邱可新** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/hooks?pullRequest=470) it.</sub>

2020-07-01 12:48 UTC, awmleer requested changes

2020-07-01 12:48 UTC, awmleer commented on packages/hooks/src/useInterval/index.zh-CN.md
> +useInterval(fn: () => void, interval: number, options?: options);
```suggestion
useInterval(fn: () => void, interval: number, options?: Options);
```

2020-07-01 12:48 UTC, awmleer commented on packages/hooks/src/useInterval/index.zh-CN.md
> +  path: /state
```suggestion
  title: SideEffect
  path: /side-effect
```

2020-07-01 12:48 UTC, awmleer commented on packages/hooks/src/useInterval/index.en-US.md
> +  path: /state
```suggestion
  title: SideEffect
  path: /side-effect
```

2020-07-01 12:48 UTC, awmleer commented on packages/hooks/src/useInterval/index.en-US.md
> +useInterval(fn: () => void, interval: number, options?: options);
```suggestion
useInterval(fn: () => void, interval: number, options?: Options);
```

2020-07-01 12:48 UTC, awmleer commented on packages/hooks/src/useInterval/index.en-US.md
> +| options | Config the interval behavior. See the Options section below.  | options |
```suggestion
| options | Config the interval behavior. See the Options section below.  | Options |
```

2020-07-01 12:48 UTC, awmleer commented on packages/hooks/src/useInterval/index.ts
> +  interval: number,
这个参数叫 delay 可能更贴切，参考 MDN 上 [setInterval 的文档](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval)

2020-07-01 12:48 UTC, awmleer commented on packages/hooks/src/useInterval/index.ts
> +    let timer: NodeJS.Timeout;
timer 的类型是 number 啊，我们是浏览器环境，怎么这里突然冒出来个 `NodeJS`

2020-07-01 12:48 UTC, awmleer commented on packages/hooks/src/useInterval/index.ts
> +    if (typeof interval !== 'undefined' || interval !== null) {
if 条件可以上提成：
```
if (interval === undefined || interval === null) return
```

2020-07-01 12:48 UTC, awmleer commented on packages/hooks/src/useInterval/index.ts
> +    if (typeof interval !== 'undefined' || interval !== null) {
而且位置可以放到最上面，这样 timer 就不用手动提前定义了，可以直接用 ts 类型推导

2020-07-01 12:48 UTC, awmleer commented on packages/hooks/src/useInterval/index.ts
> +        timerRef?.current();
`timerRef` 为啥需要 `?.` ？应该是 `timerRef.current?.()` 吧

2020-07-01 12:48 UTC, awmleer commented on packages/hooks/src/useInterval/index.ts
> +  const timerRef = useRef<{ (): void }>();
```suggestion
  const timerRef = useRef<() => void>();
```

2020-07-02 02:28 UTC, awmleer requested changes

2020-07-02 02:28 UTC, awmleer commented on packages/hooks/src/useInterval/index.zh-CN.md
> +| delay | 间隔时间 | number |
```suggestion
| delay | 间隔时间，当取值为 `null` 或 `undefined` 时会停止计时器 | number \| undefined \| null |
```

2020-07-02 02:28 UTC, awmleer commented on packages/hooks/src/useInterval/index.en-US.md
> +| delay | The timer should delay in between executions of the specified function or code | number |
```suggestion
| delay | The timer should delay in between executions of the specified function or code. If delay is `null` or `undefined`, the timer will stop. | number \| undefined \| null |
```

2020-07-02 08:07 UTC, awmleer reviewed
整体 LGTM 了，不过还是有两个地方可以优化一下～
1. demo 有点复杂，可以考虑拆成两个 demo，一个简单用法和一个稍微进阶版的用法
2. 补齐测试用例

2020-07-05 10:34 UTC, brickspert reviewed
其它建议同 #卡晨 一样

2020-07-05 10:34 UTC, brickspert commented on packages/hooks/src/useInterval/demo/demo1.tsx
> +  function log() {
log 和 immediateLog 不用单独抽出来函数，本来就一行代码。

2020-07-06 06:57 UTC, awmleer requested changes

2020-07-06 06:57 UTC, awmleer commented on packages/hooks/src/useInterval/demo/demo1.tsx
>      { immediate: false },
这一行可以去掉 `{ immediate: false },`

2020-07-06 07:03 UTC, awmleer approved these changes
LGTM

2020-07-06 13:04 UTC, brickspert commented on packages/hooks/src/useInterval/__tests__/index.test.ts
> +      await sleep(700);
这样不太友好，这样是真的等了 700 ms。可以使用 `jest.advanceTimersByTime(700)` 来模拟

2020-07-06 13:05 UTC, brickspert commented on packages/hooks/src/useInterval/index.ts
> +  delay: number,
这个 delay 的类型不太对吧？

2020-07-06 13:07 UTC, awmleer commented on packages/hooks/src/useInterval/index.ts
> +  delay: number,
嗯。。应该是 `number | null | undefined`

2020-07-10 03:44 UTC, awmleer approved these changes
LGTM

2020-07-10 03:45 UTC, merged