feat: reset history in useHistoryTravel
alibaba/hooks pull request #523
Opened 2020-07-18 18:00 UTC by jinixx

Method to reset history to initial value or with a new initial value.

2020-07-18 18:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/hooks?pullRequest=523) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/hooks?pullRequest=523) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/hooks?pullRequest=523) it.</sub>

2020-07-21 01:48 UTC, brickspert commented
You should provide an example for reset.

2020-07-22 05:07 UTC, jinixx commented
> You should provide an example for reset.

Example and demo added.

2020-07-22 11:52 UTC, brickspert requested changes

2020-07-22 11:52 UTC, brickspert commented on packages/hooks/src/useHistoryTravel/index.ts
> +
```suggestion

  const initialValueRef = useRef(initialValue);

  const reset = useCallback(
    () => {
      setHistory({
        present: initialValueRef.current,
        future: [],
        past: []
      });
    },
    [setHistory]
  );
```

reset 可以搞的简单一些，不需要修改初始值。

2020-07-22 11:52 UTC, brickspert commented on packages/hooks/src/useHistoryTravel/demo/demo1.tsx
> +        <button type="button" disabled={!backLength && !forwardLength} onClick={onReset}>
应该和前面的按钮有个边距

2020-07-23 02:52 UTC, jinixx commented on packages/hooks/src/useHistoryTravel/index.ts
> +
without this, how can I implement a similar feature if the game board layout has changed?

```
const initialBoardData = useMemo(() => getBoardLayout(config), [config]);

const {
    value,
    setValue,
    backLength,
    forwardLength,
    back,
    forward,
    go,
    reset
} = useHistoryTravel({
    ...initialStateForTimeTravel,
    boardData: initialBoardData
});
```

2020-07-23 02:56 UTC, jinixx commented on packages/hooks/src/useHistoryTravel/demo/demo1.tsx
> +        <button type="button" disabled={!backLength && !forwardLength} onClick={onReset}>
Sorry, I don't understand this.

2020-07-23 11:05 UTC, brickspert commented on packages/hooks/src/useHistoryTravel/index.ts
> +
I have modified the suggested code~~

2020-07-23 11:06 UTC, brickspert commented on packages/hooks/src/useHistoryTravel/demo/demo1.tsx
> +        <button type="button" disabled={!backLength && !forwardLength} onClick={onReset}>
Sorry，I mean we need to add a margin between the buttons

2020-07-23 18:24 UTC, jinixx commented on packages/hooks/src/useHistoryTravel/index.ts
> +
@brickspert your suggestion is similar to my first attempt. But, I amended it after I realised from the tests that undefined is a valid initialValue. Reset should allow setting initialValue to undefined as well.

2020-07-24 01:52 UTC, brickspert commented on packages/hooks/src/useHistoryTravel/index.ts
> +
reset is a bit troublesome to set two parameters  for one thing.

 or you can use like this

```js
const reset = (...params)=>{
   if(params.length > 0){
      ...
   }else{
      ...
   }
}
```

in this code , `reset()` is not equal to `reset(undefined)`.

2020-07-24 11:24 UTC, brickspert approved these changes
LGTM

2020-07-24 11:27 UTC, ttys026 approved these changes
LGTM

2020-07-24 11:29 UTC, merged