fix: validate form before submit
alibaba/hooks pull request #547
Opened 2020-07-25 05:40 UTC by monkindey

Close https://github.com/alibaba/hooks/issues/511

2020-07-26 02:10 UTC, brickspert commented
CI is error

2020-07-26 02:12 UTC, brickspert commented
也需要关注下 useFusionTable，是基于 useAntdTable 开发的

2020-07-26 07:34 UTC, monkindey commented
fusion test 还有问题，我再研究下。

2020-07-27 08:39 UTC, monkindey commented on packages/hooks/src/useFusionTable/__tests__/index.test.ts
> +    changeSearchType('simple');
把 searchType 重置下，不然会影响到其他测试用例

2020-07-27 08:41 UTC, monkindey commented on packages/hooks/src/useFusionTable/__tests__/index.test.ts
> +    changeSearchType('advance');
修改下 advance searchType，不然下面的

```js
expect(queryArgs.phone).toEqual('123');
```

会报错，因为 simple 模式 getNames 只有 name

2020-07-27 08:43 UTC, monkindey commented on packages/hooks/src/useFusionTable/__tests__/index.test.ts
> -    jest.useFakeTimers();
把 fake timers 去掉了，不知道为什么用了这个会导致放在 Promise 里面 setTimeout 的函数一直不执行，而且 useAntTable 的测试用例也不需要 fake timers。按理说下面用了 

```js
await hook.waitForNextUpdate();	
```

是不需要 fake timer 来控制 timer 执行的。

2020-07-27 08:44 UTC, monkindey commented
@brickspert  老哥，你可以再看下了。加了 fusion table 和 解决测试用例失败。

2020-07-27 13:19 UTC, brickspert commented on packages/hooks/src/useAntdTable/index.ts
> +      validateFields()
antd3 这里有问题，validateFileds 需要指定当前激活的字段的具体名称。

我举个例子：

1. 在 demo5.tsx 中给 email 设置一个 require，然后清空，此时表单是不能通过校验的
2. 切换到建议模式，此时已经没有 email 字段了，但表单还是不能通过校验。

因为 antd3 有这种 bug，已经删除的 filed，还是会校验。

所以这里可以通过 getActivetFieldValues 来读取到激活的 fileds，再去做 validate~~

2020-07-27 16:56 UTC, monkindey commented on packages/hooks/src/useAntdTable/index.ts
> +      validateFields()
这个事情不应该 antd3 要去解决的吗？

2020-07-28 02:10 UTC, brickspert requested changes
UseAntdTableFormUtils 这个 ts 类型也要加下 validateFileds

2020-07-28 02:10 UTC, brickspert commented on packages/hooks/src/useAntdTable/__tests__/index.test.ts
> +    await sleep(1);
```suggestion
    await hook.waitForNextUpdate();
```

2020-07-28 02:10 UTC, brickspert commented on packages/hooks/src/useAntdTable/index.ts
> +      validateFields()
antd3 getFiledsValue 和 validateFfiledsValue 都有类似的问题~

antd3 不会做 break change

2020-07-28 02:10 UTC, brickspert commented on packages/hooks/src/useFusionTable/__tests__/index.test.ts
> +    changeSearchType('advance');
应该不会吧，因为设置了默认的 type `defaultType`，那应该类型已经是 `advance` 了

2020-07-28 02:10 UTC, brickspert commented on packages/hooks/src/useFusionTable/__tests__/index.test.ts
> +    changeSearchType('advance');
感觉如果把 validatFields 放到 setTimeout 里面，这些测试用例应该就都对了。

我猜的~

2020-07-28 03:24 UTC, monkindey commented
> 应该不会吧，因为设置了默认的 type defaultType，那应该类型已经是 advance 了

如果你把 test 上面的 "should form, defaultPageSize, id work" 测试用例关了，你会发现下面的测试用例跑不通。

2020-07-28 08:05 UTC, brickspert commented
CI 没过

2020-07-28 09:22 UTC, monkindey commented
> CI 没过

Required 的 CI 都过了。

2020-07-28 11:56 UTC, brickspert approved these changes
LGTM

2020-07-28 12:35 UTC, monkindey commented
useCookieState CI 好像跪了？

2020-07-28 12:45 UTC, brickspert commented on packages/hooks/src/useCookieState/index.ts
> -      const { defaultValue, ...restOptions } = { ...options, ...newOptions };
我去，你为啥改了这个代码。。。

2020-07-28 13:10 UTC, tli4 commented on packages/hooks/src/useAntdTable/index.ts
> +    return form.validateFields(fields);
antd 3 的 validateFields 不能接 .then 吧，这里要分开处理下

2020-07-28 13:11 UTC, brickspert commented on packages/hooks/src/useAntdTable/index.ts
> +    return form.validateFields(fields);
我测试应该是可以的~

2020-07-28 13:26 UTC, monkindey commented on packages/hooks/src/useAntdTable/index.ts
> +    return form.validateFields(fields);
好奇怪，我居然用 antd3 能跑起来。好像 antd3 用的 rc-form 是 `2.4.10` 版本，而 2.4.10 版本的返回就是一个 [Promise](https://github.com/react-component/form/blob/master/src/createBaseForm.js#L587)

2020-07-30 01:41 UTC, brickspert commented on packages/hooks/src/useAntdTable/index.ts
> +    return form.validateFields(fields);
这个要修下的吧~

2020-08-02 07:50 UTC, monkindey commented on packages/hooks/src/useAntdTable/index.ts
> +    return form.validateFields(fields);
处理了，可以再看下

2020-08-02 11:03 UTC, ttys026 approved these changes
legit

2020-08-02 11:14 UTC, merged