Feat/use network
alibaba/hooks pull request #569
Opened 2020-08-07 07:42 UTC by Straw94

管理NetworkInformation 对象，其中包含有关系统连接的信息

### api
```javascript
interface INetworkState {
  rtt?: number;
  since?: Date;
  type?: string;
  online?: boolean;
  downlink?: number;
  saveData?: boolean;
  downlinkMax?: number;
  effectiveType?: string;
}

const networkState: INetworkState = useNetwork(
  defaultValue?: INetworkState | (() => INetworkState),
);

```

2020-08-07 07:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/hooks?pullRequest=569) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/hooks?pullRequest=569) before we can accept your contribution.<br/><hr/>**稻草** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/hooks?pullRequest=569) it.</sub>

2020-08-07 13:06 UTC, brickspert requested changes

2020-08-07 13:06 UTC, brickspert commented on packages/hooks/src/useNetwork/demo/demo1.tsx
> + * desc.zh-CN: 默认切换布尔值状态，也可以接收一个参数作为新的值
这句话没看懂

2020-08-07 13:06 UTC, brickspert commented on packages/hooks/src/useNetwork/index.en-US.md
> +interface INetworkState {
目前整个 ahooks 的类型都没有以 I 开头，建议统一。

2020-08-07 13:06 UTC, brickspert commented on packages/hooks/src/useNetwork/index.ts
> +function isFunc(v: Function | INetworkState): v is Function {
```suggestion
function isFunc(v: any): Boolean {
```

2020-08-07 13:06 UTC, brickspert commented on packages/hooks/src/useNetwork/index.ts
> +  const [state, setState] = useState(isFunc(initialState) ? initialState() : initialState);
```suggestion
  const [state, setState] = useState(initialState);
```

2020-08-07 13:06 UTC, brickspert commented on packages/hooks/src/useNetwork/index.ts
> +        ...(connection && {
这里感觉不太对呀， connection 永远都不会变。

监听到 onChange，执行 onConnectionChange，但是 connection 没有变

2020-08-08 13:10 UTC, Straw94 commented on packages/hooks/src/useNetwork/index.ts
> +function isFunc(v: Function | INetworkState): v is Function {
这个其实是已经限定了类型吧

2020-08-08 13:12 UTC, Straw94 commented on packages/hooks/src/useNetwork/index.ts
> +  const [state, setState] = useState(isFunc(initialState) ? initialState() : initialState);
👌

2020-08-09 08:30 UTC, brickspert commented on packages/hooks/src/useNetwork/index.zh-CN.md
> +| defaultValue | Optional，set a default networkState value  | NetworkState \| () => NetworkState | {} |
中文？

2020-08-09 08:30 UTC, brickspert commented on packages/hooks/src/useNetwork/index.ts
> +function isFunc(v: Function | NetworkState): v is Function {
这个没用了

2020-08-09 08:30 UTC, brickspert commented on packages/hooks/src/useNetwork/index.ts
> +  const [state, setState] = useState(initialState);
如果用户没有传 initialState，直接返回了空对象，没有初始值。

![image](https://user-images.githubusercontent.com/12526493/89728051-df836c80-da5c-11ea-9d77-63dd6057af56.png)

2020-08-09 12:51 UTC, Straw94 commented on packages/hooks/src/useNetwork/index.ts
> +  const [state, setState] = useState(initialState);
fix

2020-08-09 12:52 UTC, Straw94 commented on packages/hooks/src/useNetwork/index.en-US.md
> +interface INetworkState {
fix

2020-08-09 12:52 UTC, Straw94 commented on packages/hooks/src/useNetwork/index.ts
> +        ...(connection && {
fix

2020-08-09 12:52 UTC, Straw94 commented on packages/hooks/src/useNetwork/index.zh-CN.md
> +| defaultValue | Optional，set a default networkState value  | NetworkState \| () => NetworkState | {} |
fix

2020-08-11 08:08 UTC, brickspert approved these changes

2020-08-11 10:15 UTC, awmleer approved these changes
LGTM

2020-08-11 10:21 UTC, merged