fix(useHistoryTravel): fix Implicit-Conversion
alibaba/hooks pull request #582
Opened 2020-08-11 13:18 UTC by linbudu599

2020-08-11 13:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/hooks?pullRequest=582) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/hooks?pullRequest=582) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/hooks?pullRequest=582) it.</sub>

2020-08-12 01:41 UTC, brickspert requested changes

2020-08-12 01:41 UTC, brickspert commented on packages/hooks/src/useHistoryTravel/index.ts
> +      : // avoid Implicit-Conversion
最好在入口处就把类型校正对，入口是 `go` 函数

```js
  const go = useCallback(
    (step: number) => {
      const convertedStep = Number(step);
      if (convertedStep === 0) {
        return;
      }
      if (convertedStep > 0) {
        return _forward(step);
      }
      _backward(convertedStep);
    },
    [_backward, _forward],
  );
```

2020-08-12 02:01 UTC, linbudu599 commented
已修正，在`go()`中做了类型处理
```typescript
const go = useCallback(
    (step: number) => {
      const stepNum = typeof step === 'number' ? step : Number(step);
      if (stepNum === 0) {
        return;
      }
      if (stepNum > 0) {
        return _forward(step);
      }
      _backward(stepNum);
    },
    [_backward, _forward]
  );
```

2020-08-12 02:04 UTC, linbudu599 commented
已修正：
```typescript
const go = useCallback(
    (step: number) => {
      const stepNum = typeof step === 'number' ? step : Number(step);
      if (stepNum === 0) {
        return;
      }
      if (stepNum > 0) {
        return _forward(stepNum);
      }
      _backward(stepNum);
    },
    [_backward, _forward]
  );
```

2020-08-12 12:42 UTC, brickspert approved these changes
LGTM

2020-08-12 12:42 UTC, merged