useCountDown Hook
alibaba/hooks pull request #619
Opened 2020-08-30 06:46 UTC by linbudu599

Related Issue #576

2020-08-30 06:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/hooks?pullRequest=619) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/hooks?pullRequest=619) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/hooks?pullRequest=619) it.</sub>

2020-08-31 14:07 UTC, brickspert requested changes
src/index 需要导出一下

2020-08-31 15:18 UTC, brickspert requested changes

2020-08-31 15:18 UTC, brickspert commented on packages/hooks/src/useCountDown/demo/demo2.tsx
> +const timeEnd = Date.now() + 5000;
```suggestion
const timeEnd = () => (Date.now() + 5000);
```
这里应该是个函数，否则会有问题。

2020-08-31 15:18 UTC, brickspert commented on packages/hooks/src/useCountDown/demo/demo2.tsx
> +import useCountDown from '../index';
```suggestion
import useCountDown from 'ahooks';
```

2020-08-31 15:18 UTC, brickspert commented on packages/hooks/src/useCountDown/demo/demo1.tsx
> +import useCountDown from '../index';
```suggestion
import useCountDown from 'ahooks';
```

2020-08-31 15:18 UTC, brickspert commented on packages/hooks/src/useCountDown/demo/demo3.tsx
> +import useCountDown from '../index';
```suggestion
import useCountDown from 'ahooks';
```

2020-08-31 15:18 UTC, brickspert commented on packages/hooks/src/useCountDown/demo/demo3.tsx
> +const timeEnd = Date.now() + 3000;
```suggestion
const timeEnd = () => (Date.now() + 3000);
```

2020-08-31 15:18 UTC, brickspert commented on packages/hooks/src/useCountDown/index.zh-CN.md
> +一个用于 管理倒计时 的Hook..
```suggestion
一个用于 管理倒计时 的Hook。
```

2020-08-31 15:18 UTC, brickspert commented on packages/hooks/src/useCountDown/demo/demo1.tsx
> +        距离 2020年12月31日 24:00:00 还有 {days} 天 {hours} 小时 {minutes} 分钟 {seconds} 秒
用英文

2020-08-31 15:18 UTC, brickspert commented on packages/hooks/src/useCountDown/index.ts
> +  const [formattedRes, setFormattedRes] = useState<FormattedRes>(parser(timeLeft, formatter));
formattedRes 不用定义一个 useState 吧~~
输出之前计算下就好了，类似下面。

```
const formattedRes = useMemo(()=> parser(timeLeft, formatter), [timeLeft, formatter]);
```

2020-08-31 15:18 UTC, brickspert commented on packages/hooks/src/useCountDown/index.ts
> +    (targetDate?: TDate) => new Date(targetDate ?? target ?? Date.now()).getTime() - dateFrom,
如果 targetDate 和 dateFrom 都有值，那这里应该永远不会变化了。

2020-08-31 15:18 UTC, brickspert commented on packages/hooks/src/useCountDown/index.ts
> +    (targetDate?: TDate) => new Date(targetDate ?? target ?? Date.now()).getTime() - dateFrom,
还是不要 dateFrom 了

2020-08-31 15:18 UTC, brickspert commented on packages/hooks/src/useCountDown/index.ts
> +export type TOpts = {
类型的名字就叫 Options 好了，和其它 hooks 统一

2020-08-31 15:18 UTC, brickspert commented on packages/hooks/src/useCountDown/index.ts
> +  }, [intervalTime, dateEnd, timeLeft]);
这里的依赖需要梳理下， target 应该是依赖的一项把，而 dateEnd 不是依赖。

2020-09-01 03:36 UTC, linbudu599 commented on packages/hooks/src/useCountDown/index.ts
> +    (targetDate?: TDate) => new Date(targetDate ?? target ?? Date.now()).getTime() - dateFrom,
那是否要固定dateFrom为当前时间呢🤣

2020-09-01 04:37 UTC, linbudu599 commented on packages/hooks/src/useCountDown/demo/demo2.tsx
> +const timeEnd = Date.now() + 5000;
我看了一下, 这里如果是函数, 会缓存掉这个`Date.now()`, 比如多次启用计时器间隔会递增, 比如5 10 15这样. 然后这种直接传入`Date.now`的方式, 每次反而会重新计算.
但我发现了另外一个问题,  传入`Date.now()`, 由于程序运行的时间, 有可能手动启用时的时间戳不到5000, 会是499x这种, 导致计时器少1s.
我尝试过传入函数然后在内部调用, 同样会有问题. 除非是像我另外一个包的写法直接传入秒数来计时: [use-verify-code](https://github.com/PenumbraPro/react-useVerifyCode-hook)

有什么好的建议吗2333

2020-09-01 14:43 UTC, brickspert commented on packages/hooks/src/useCountDown/index.ts
> +    (targetDate?: TDate) => new Date(targetDate ?? target ?? Date.now()).getTime() - dateFrom,
calcLeft 是计算 当前时间(new Date()) 到 目标时间(targetDate) 的间隔的。

和 dateFrom 没啥关系吧。

2020-09-01 14:46 UTC, brickspert commented on packages/hooks/src/useCountDown/demo/demo2.tsx
> +const timeEnd = Date.now() + 5000;
这样写会有问题吗？感觉不会吧~

```js
<button
  onClick={()=> { setTargetDate( new Date() + 5000 ) }}
>
Start Interval
</button>
```

2020-09-02 02:48 UTC, linbudu599 commented on packages/hooks/src/useCountDown/demo/demo2.tsx
> +const timeEnd = Date.now() + 5000;
会的 仍然是后续都会使用启用时的时间戳

2020-09-02 02:50 UTC, linbudu599 commented on packages/hooks/src/useCountDown/index.ts
> +    (targetDate?: TDate) => new Date(targetDate ?? target ?? Date.now()).getTime() - dateFrom,
> calcLeft 是计算 当前时间(new Date()) 到 目标时间(targetDate) 的间隔的。
> 
> 和 dateFrom 没啥关系吧。

当前的实现里是允许用户定义起始时间的, 比如12月12日距离12月1日, 只有用户不传dateFrom的情况下才使用当前时间

2020-09-02 05:45 UTC, brickspert commented on packages/hooks/src/useCountDown/demo/demo2.tsx
> +const timeEnd = Date.now() + 5000;
那感觉是不是代码逻辑的问题。
这个代码应该是期望的正确用法吧。

2020-09-02 15:08 UTC, brickspert commented on packages/hooks/src/useCountDown/index.ts
> +    (targetDate?: TDate) => new Date(targetDate ?? target ?? Date.now()).getTime() - dateFrom,
dateFrom 是指开始时间，如果没有到开始时间，返回的  countdown 应该是不变的。
如果已经到了开始时间，返回的 countdown 才会递减。

2020-09-03 02:09 UTC, linbudu599 commented on packages/hooks/src/useCountDown/index.ts
> +    (targetDate?: TDate) => new Date(targetDate ?? target ?? Date.now()).getTime() - dateFrom,
get√

2020-09-03 02:20 UTC, linbudu599 commented on packages/hooks/src/useCountDown/demo/demo2.tsx
> +const timeEnd = Date.now() + 5000;
done √

2020-09-03 02:23 UTC, linbudu599 commented on packages/hooks/src/useCountDown/index.ts
> +  const [formattedRes, setFormattedRes] = useState<FormattedRes>(parser(timeLeft, formatter));
done √

2020-09-03 02:30 UTC, linbudu599 commented on packages/hooks/src/useCountDown/index.ts
> +    (targetDate?: TDate) => new Date(targetDate ?? target ?? Date.now()).getTime() - dateFrom,
那我这里就先移除dateFrom支持吧

2020-09-03 03:15 UTC, linbudu599 commented on packages/hooks/src/useCountDown/demo/demo2.tsx
> +const timeEnd = Date.now() + 5000;
又试了一些方法, 感觉只要以`Date.now()`来调用就会有问题, 比如上面的`setTargetDate( new Date() + 5000 )`调用方式, 我适配了后发现这个`Date.now()`是在组件首次渲染完成就固定的, 除非你立刻点击, 不然计时时间就会变长...  代码的实现我贴一下  [Demo](https://codesandbox.io/s/morning-cloud-v046x?file=/src/useCountDown.ts) 只有立刻点击才是正常的. 可能还需要再思考下怎么解决这个问题

2020-09-07 12:11 UTC, brickspert commented
先合并了，然后我再修正一波。

2020-09-07 12:12 UTC, merged