feat: add useCountDown
alibaba/hooks pull request #636
Opened 2020-09-07 15:56 UTC by brickspert

2020-09-07 15:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/hooks?pullRequest=636) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/hooks?pullRequest=636) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: brickspert<br/>:x: linbudu599<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/hooks?pullRequest=636) it.</sub>

2020-09-08 01:53 UTC, brickspert commented
@linbudu599

2020-09-08 03:13 UTC, awmleer requested changes

2020-09-08 03:13 UTC, awmleer commented on packages/hooks/src/useCountDown/demo/demo1.tsx
> +        milliseconds until 2020年12月31日 24:00:00
demo 这里还是统一用英文比较好。。

2020-09-08 03:13 UTC, awmleer commented on packages/hooks/src/useCountDown/index.ts
> +  }, []);
这个函数是不是可以直接移到 `useCountDown` 的外面去？

2020-09-08 03:13 UTC, awmleer commented on packages/hooks/src/useCountDown/index.ts
> +  }, []);
而且也没有必要 useCallback。。

2020-09-08 03:13 UTC, awmleer commented on packages/hooks/src/useCountDown/index.ts
> +      if (timer) {
这里为啥要 `if (timer)` 啊。。timer 不是一定不为空么

2020-09-08 03:56 UTC, brickspert commented on packages/hooks/src/useCountDown/index.ts
> +      if (timer) {
前面还有个 clearInterval，在时间到 0  时，还会清空一次。

2020-09-08 04:11 UTC, awmleer commented on packages/hooks/src/useCountDown/index.ts
> +      if (timer) {
但是 `clearInterval` 了也不会改变 `timer` 的值啊。。

2020-09-08 05:35 UTC, brickspert commented on packages/hooks/src/useCountDown/index.ts
> +      if (timer) {
好像是，fixed

2020-09-08 05:59 UTC, awmleer approved these changes
LGTM

2020-09-08 09:17 UTC, merged