Feat/use favicon
alibaba/hooks pull request #641
Opened 2020-09-09 03:14 UTC by linbudu599

see #581 for details.

2020-09-09 03:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/hooks?pullRequest=641) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/hooks?pullRequest=641) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/hooks?pullRequest=641) it.</sub>

2020-09-09 06:30 UTC, brickspert commented on packages/hooks/src/useFavicon/index.en-US.md
> +Set or Configure Page Favicon URL.
```suggestion
Set or configure page favicon URL.
```

2020-09-09 06:30 UTC, brickspert commented on packages/hooks/src/useFavicon/index.zh-CN.md
> +| faviconURL | favicon地址 | string | 无     |
可以说明支持 xxx 类型

2020-09-10 00:49 UTC, linbudu599 commented on packages/hooks/src/useFavicon/index.zh-CN.md
> +| faviconURL | favicon地址 | string | 无     |
done

2020-09-10 01:55 UTC, brickspert approved these changes
LGTM

2020-09-10 04:43 UTC, awmleer requested changes

2020-09-10 04:43 UTC, awmleer commented on packages/hooks/src/useFavicon/index.ts
> +const ImgTypeMap = {
```suggestion
const imgTypeMap = {
```

这里应该是小驼峰

2020-09-10 04:43 UTC, awmleer commented on packages/hooks/src/useFavicon/index.ts
> +    document.getElementsByTagName('head')[0].appendChild(link);
这里是不是少了 clean up 操作？

2020-09-10 05:08 UTC, linbudu599 commented on packages/hooks/src/useFavicon/index.ts
> +    document.getElementsByTagName('head')[0].appendChild(link);
是需要把`link`置为null吗

2020-09-10 05:14 UTC, awmleer commented on packages/hooks/src/useFavicon/index.ts
> +    document.getElementsByTagName('head')[0].appendChild(link);
`removeChild(link)`

2020-09-10 05:37 UTC, brickspert commented on packages/hooks/src/useFavicon/index.ts
> +    document.getElementsByTagName('head')[0].appendChild(link);
我当时测试了，应该是会自动 remove 的

2020-09-10 06:23 UTC, linbudu599 commented on packages/hooks/src/useFavicon/index.ts
> +    document.getElementsByTagName('head')[0].appendChild(link);
> 我当时测试了，应该是会自动 remove 的

是的哇

2020-09-10 07:01 UTC, awmleer approved these changes

2020-09-10 08:12 UTC, merged