optimize: useEventListener
alibaba/hooks pull request #678
Opened 2020-10-10 08:41 UTC by brickspert

2020-10-13 12:55 UTC, brickspert commented on packages/hooks/src/useEventListener/index.ts
> +    typeof options.target === 'function' ? options.target() : options.target,
```suggestion
    typeof options.target === 'function' ? undefined : options.target,
```

2020-10-15 04:19 UTC, awmleer requested changes

2020-10-15 04:19 UTC, awmleer commented on packages/hooks/src/useEventListener/index.ts
>          capture: options?.capture,
这里应该也不需要 `?.` 了

2020-10-15 11:06 UTC, brickspert commented on packages/hooks/src/useEventListener/index.ts
>          capture: options?.capture,
```suggestion
        capture: options.capture,
```

2020-10-16 07:32 UTC, awmleer approved these changes
LGTM

2020-10-16 07:32 UTC, merged