feat: useUnmountedRef
alibaba/hooks pull request #766
Opened 2020-12-04 04:15 UTC by syfless1999

使用hooks实现获取当前组件是否已经卸载的状态，避免因为组件卸载后修改状态而造成的内存泄漏

2020-12-04 05:03 UTC, awmleer requested changes

2020-12-04 05:03 UTC, awmleer commented on packages/hooks/src/useUnmountedRef/index.ts
> +  const unmountRef = useRef(true);
这里的默认值应该是 true 还是 false？

2020-12-04 05:03 UTC, awmleer commented on packages/hooks/src/useUnmountedRef/index.zh-CN.md
> +const unmountRef: { current: boolean } = useUnmountedRef;
`unmountRef` -> `unmountedRef`

2020-12-04 05:03 UTC, awmleer commented on packages/hooks/src/useUnmountedRef/index.ts
> +  const unmountRef = useRef(true);
既然是 unmounted，应该是“是否已卸载”，所以没 mount 的时候也不算 unmounted 吧……之前 @brickspert 不建议叫 use MountedRef，大概就是因为这个？

2020-12-04 05:29 UTC, syfless1999 commented on packages/hooks/src/useUnmountedRef/index.ts
> +  const unmountRef = useRef(true);
有道理

2020-12-05 03:16 UTC, syfless1999 commented
嗯我又改了一版

2020-12-05 03:30 UTC, awmleer approved these changes
LGTM

2020-12-06 08:50 UTC, brickspert approved these changes

2020-12-06 08:50 UTC, merged