feat(hooks): add a new hook named useExternal and write the example with contribution guide.
alibaba/hooks pull request #775
Opened 2020-12-07 06:50 UTC by Turkyden

哈喽, 之前对于新增 `hooks/useExternal` 的提议 #758 已通过评审，现在提个 PR，望采纳，感谢！ 

@brickspert

2020-12-07 06:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/hooks?pullRequest=775) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/hooks?pullRequest=775) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/hooks?pullRequest=775) it.</sub>

2020-12-08 12:52 UTC, brickspert commented on packages/hooks/src/useExternal/index.ts
> +  const [src, setSrc] = useState(path);
path 和 src 两个属性有点冗余了。

现在提供了两种方案来修改资源路径，一个是 path 变化，一个是 load/toggle 函数。
建议只保留 path，不要 src 了。也就是 load 和 toggle 的时候不再接收参数。

2020-12-09 01:08 UTC, Turkyden commented on packages/hooks/src/useExternal/index.ts
> +  const [src, setSrc] = useState(path);
这一点我也纠结了很久，OK, 那我改一改再提 PR 哈，感谢反馈！

2020-12-10 02:03 UTC, Turkyden commented
哈喽，已经修改，再次 PR ！@brickspert

2020-12-10 12:03 UTC, brickspert approved these changes
LGTM

2020-12-11 03:48 UTC, awmleer requested changes

2020-12-11 03:48 UTC, awmleer commented on packages/hooks/src/useExternal/index.ts
> +export default function useScript(path: string, options?: Options): [Status, Action] {
这里的函数名为啥是 `useScript`

2020-12-11 03:48 UTC, awmleer commented on packages/hooks/src/useExternal/index.ts
> +  }, [active]);
这里是不是可以这样优化一下

```suggestion
  const action = useMemo(() => {
    const unload = () => setActive(false);
    const load = () => setActive(true);
    const toggle = () => setActive(val => !val);
    return { toggle, load, unload };
  }, [setActive]);
```

2020-12-11 03:48 UTC, awmleer commented on packages/hooks/src/useExternal/index.ts
> +  const ref = useRef<ExternalElement>();
这里为啥要用一个 ref，可以直接在下面的 `useEffect` 中用一个局部变量实现么

2020-12-11 09:22 UTC, Turkyden commented on packages/hooks/src/useExternal/index.ts
> +export default function useScript(path: string, options?: Options): [Status, Action] {
噢，我统一成 `useExternal` 吧。

2020-12-11 09:22 UTC, Turkyden commented on packages/hooks/src/useExternal/index.ts
> +  }, [active]);
确实这样更优雅！我改一下哈。

2020-12-11 10:36 UTC, Turkyden commented on packages/hooks/src/useExternal/index.ts
> +  const ref = useRef<ExternalElement>();
这里的 ref 我考虑是用于存储当前外链资源的 dom 实例，如果不使用 ref，当 path 是动态改变的时候，useExternal 将无法移除之前旧的 dom. @awmleer

2020-12-11 10:39 UTC, Turkyden commented on packages/hooks/src/useExternal/index.ts
> +  const ref = useRef<ExternalElement>();
```js
const [ status, toggle ] = useExternal(path, {})
```
path 如果动态传值的话，如果不用 ref 存储住外链 dom，貌似无法移除旧的外链 dom。

2020-12-11 14:40 UTC, Turkyden commented on packages/hooks/src/useExternal/index.ts
> +  const ref = useRef<ExternalElement>();
> 这里为啥要用一个 ref，可以直接在下面的 `useEffect` 中用一个局部变量实现么

这里的 ref 我是这样考虑的，它的作用是存储当前外链资源的 DOM 引用。

```js
const [ status, { load, unload, toggle } ] = useExternal(path, options);
```

如果不用 ref 存储住外链资源的 DOM 引用，当参数 `path`  是动态传入时，`useExternal` 貌似无法移除之前加载的外链 DOM，然后替换新的外链资源。

我暂时还想不到更好的解决办法，因此，`useEffect` 中使用局部变量貌似无法实现这个需求。 

@awmleer

2020-12-14 07:51 UTC, ouzhou commented
为啥不叫use script

2020-12-14 07:53 UTC, Turkyden commented
> 为啥不叫use script

因为不仅仅用于加载 js 哦，还可以加载 css, img 这些外链资源。

2020-12-15 04:05 UTC, ouzhou commented
看起来似乎是CI在拉取git的时候报错了 @Turkyden 
很期待这个hook能使用

2020-12-15 06:08 UTC, Turkyden commented
> 看起来似乎是CI在拉取git的时候报错了 @Turkyden
> 很期待这个hook能使用

是的，这个新 hook 在等待 @awmleer 的 review 哦。

2020-12-15 10:08 UTC, awmleer approved these changes
LGTM

2020-12-15 11:22 UTC, merged

2021-01-09 03:39 UTC, KrishnaPG commented
This is a good starting point, and very useful to inject dynamic dependencies from CDN. However, few important pieces are missing in the functionality:

1. Duplicates should be avoided. For example, multiple instances of a component injecting the same CSS or Script should be handled
2. `useExternal` should be able to add more than one script/css at a time. That is, should support array of URLs in case more than one is to be injected
3. Unloading the script/css should be taken care of.

2021-01-10 06:53 UTC, brickspert commented
> This is a good starting point, and very useful to inject dynamic dependencies from CDN. However, few important pieces are missing in the functionality:
> 
> 1. Duplicates should be avoided. For example, multiple instances of a component injecting the same CSS or Script should be handled
> 2. `useExternal` should be able to add more than one script/css at a time. That is, should support array of URLs in case more than one is to be injected
> 3. Unloading the script/css should be taken care of.
> 
> It would be a great value if these above also could be addressed.

Yeah, your suggestion is very good, thank you.

@TurkydenCan you support these features？

2021-11-05 10:28 UTC, wangcongyi commented on packages/hooks/src/useExternal/index.ts
> +  }, [active]);
这里为啥使用 `setActive` 作为依赖项?

2022-10-02 06:12 UTC, iShawnWang commented
> This is a good starting point, and very useful to inject dynamic dependencies from CDN. However, few important pieces are missing in the functionality:
> 
> 1. Duplicates should be avoided. For example, multiple instances of a component injecting the same CSS or Script should be handled
> 2. `useExternal` should be able to add more than one script/css at a time. That is, should support array of URLs in case more than one is to be injected
> 3. Unloading the script/css should be taken care of.
> 
> It would be a great value if these above also could be addressed.

Awesome suggestions !!! 👍