Fix/use reactive
alibaba/hooks pull request #842
Opened 2021-01-26 04:16 UTC by linbudu599

- close #839
- `use-url-state`这个包的依赖里有一部分用了内网源, 导致外网安装超时了, 我这里替换成了npm源

2021-01-26 04:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/hooks?pullRequest=842) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/hooks?pullRequest=842) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/hooks?pullRequest=842) it.</sub>

2021-01-26 06:13 UTC, awmleer requested changes

2021-01-26 06:13 UTC, awmleer commented on packages/hooks/src/useReactive/index.ts
> +const rawMap = new WeakMap();
这里是不是用 `WeakSet` 就可以了

2021-01-26 10:44 UTC, linbudu599 commented on packages/hooks/src/useReactive/index.ts
> +const rawMap = new WeakMap();
rawMap里面的键也是对象, 和proxyMap一样是值-值映射

2021-01-27 05:34 UTC, awmleer commented on packages/hooks/src/useReactive/index.ts
> +const rawMap = new WeakMap();
就是……这里 `WeakSet` 就够用了呀，当然用 `WeakMap` 肯定也不能算有问题，先这样吧～

2021-01-27 05:34 UTC, awmleer approved these changes

2021-01-27 05:34 UTC, merged