fix useScroll not work with document.body and support ios8、android4
alibaba/hooks pull request #873
Opened 2021-02-22 11:08 UTC by bloody-ux

2021-02-22 11:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/hooks?pullRequest=873) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/hooks?pullRequest=873) before we can accept your contribution.<br/><hr/>**那达** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/hooks?pullRequest=873) it.</sub>

2021-02-23 12:58 UTC, awmleer requested changes

2021-02-23 12:58 UTC, awmleer commented on packages/hooks/src/useScroll/index.ts
> +    }
这里我们不应该做处理吧……我们提供的默认值是 `document` 就可以了
如果用户自己设置成 `document.body` ，我们不应该帮他强制校正过来，如果用户就是给 `body` 增加了 `overflow: scroll` 的 css，是不是就可以触发 scroll 事件了

2021-02-23 12:58 UTC, awmleer commented on packages/hooks/src/useScroll/index.ts
> +
这里的实现不太好吧……建议还是尽量保持原来的逻辑
但是 `document.scrollingElement` 的确是有兼容性问题的：[CanIUse](https://caniuse.com/document-scrollingelement)
可以改成，在 `document.scrollingElement` 为空的时候，fallback 到 `document.documentElement`： [CanIUse](https://caniuse.com/mdn-api_document_documentelement)

2021-02-23 12:58 UTC, awmleer commented on packages/hooks/src/useScroll/index.ts
> +      el?.removeEventListener('scroll', listener);
这里为啥要判空呢？

2021-02-24 02:02 UTC, bloody-ux commented on packages/hooks/src/useScroll/index.ts
> +    }
这个问题主要在于 document.body.addEventListener('scroll') 是无法触发scroll事件的， 而通过document.body.onscroll是可以触发的。也就是说，如果用户传入document.body，假如useScroll 使用onscroll（不推荐），那么就没有问题。

添加overflow: scroll并没有用

2021-02-24 02:02 UTC, bloody-ux commented on packages/hooks/src/useScroll/index.ts
> +      el?.removeEventListener('scroll', listener);
ts会报错，不知道为什么ts在return里面的el会出现识别为空的问题

2021-02-24 02:08 UTC, closed without merging

2021-02-24 02:08 UTC, bloody-ux commented
我自己实现了一个，先不使用ahooks了，先关闭PR

2021-02-24 02:09 UTC, bloody-ux commented on packages/hooks/src/useScroll/index.ts
> +    }
看单侧里面用的也是document.body，之前的单侧其实根本不会正常工作，只因为jsdom不支持触发scroll事件