Feat/use debounce
alibaba/hooks pull request #995
Opened 2021-06-20 10:02 UTC by crazylxr

1. 更改了 lodash 的引入方式，以适应小程序环境。
2. 修改了 leading 和 trailing 的文档，之前的文案一般人根本无法理解

2021-06-20 10:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/hooks?pullRequest=995) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/hooks?pullRequest=995) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/hooks?pullRequest=995) it.</sub>

2021-06-21 02:35 UTC, awmleer requested changes

2021-06-21 02:35 UTC, awmleer commented on packages/hooks/src/useDebounce/index.zh-CN.md
> +| maxWait | 函数调用允许延迟的最长时间 | `() => void` | -  |
`maxWait` 的类型为啥是个函数嘞，不是应该 `number` 么

2021-06-21 02:35 UTC, awmleer commented on packages/hooks/src/useDebounceFn/index.ts
> +import debounce from 'lodash/debounce';
之前的 import 方式应该是没错的，ahooks 并没有直接依赖整个 lodash，`lodash.debounce` 是一个细粒度的 npm 包，具体可以看这里～
https://github.com/alibaba/hooks/blob/master/packages/hooks/package.json#L40-L42

2021-06-21 02:35 UTC, awmleer commented on packages/hooks/src/useDebounceFn/index.zh-CN.md
> +| isPending | 是否有正在挂起的函数 | `() => void` | `boolean` |
`isPending` 好像没有对应的实现？好像也不是 lodash 支持的参数

2021-06-25 03:52 UTC, crazylxr commented on packages/hooks/src/useDebounceFn/index.ts
> +import debounce from 'lodash/debounce';
lodash.debounce 这种方式会依赖一些全局的变量，在 debounce 里会使用了 root.now()，在小程序环境 global 是不存在的，用 lodash/debounce 可以避免这个问题，具体看内网 v3.0 React Hooks 在小程序环境下常见问题及解决方案

2021-06-25 03:53 UTC, crazylxr commented on packages/hooks/src/useDebounceFn/index.zh-CN.md
> +| isPending | 是否有正在挂起的函数 | `() => void` | `boolean` |
那就先不要了。。

2021-06-25 03:53 UTC, crazylxr commented on packages/hooks/src/useDebounce/index.zh-CN.md
> +| maxWait | 函数调用允许延迟的最长时间 | `() => void` | -  |
哦，对，应该是 number，这个大龙哥说也先不加了 🤣

2021-07-08 13:12 UTC, awmleer requested changes

2021-07-08 13:12 UTC, awmleer commented on packages/hooks/src/useThrottleFn/index.zh-CN.md
> +| maxWait | 函数调用允许延迟的最长时间 | `() => void` | -  |
`maxWait` 是不是要去掉？代码里好像没加这个参数

2021-07-16 12:53 UTC, awmleer requested changes

2021-07-16 12:53 UTC, awmleer commented on packages/hooks/src/utils/check.ts
> +  };
```suggestion
  if (process.env.NODE_ENV === 'development') {
    return function () {
      if (typeof arguments[0] !== 'function') {
        console.error(`${fn.name} expected parameter is a function, got '${typeof fn}`);
      }
      return fn.apply(this, arguments);
    };
  } else {
    return fn
  }
```

`production` 模式下就不要再多包一层了吧……整段逻辑都跳过

2021-07-16 12:53 UTC, awmleer commented on packages/hooks/src/utils/check.ts
> +  };
以及，这个高阶函数的命名感觉不太合适呀……

2021-07-19 09:32 UTC, closed without merging